/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Programas;

import Clases.ConeccionBD1;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import Modelo.Cliente;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Ruben
 */
public class Clientes extends javax.swing.JDialog {
    DefaultTableModel modelo = new DefaultTableModel();
 private ConeccionBD1 bd;
  private ResultSet rs;
   private boolean error;
   private Cliente cliente;
   boolean agr, mod, bor = false;
    int fila = 0;
 
    /**
     * Creates new form Clientes
     */
    public Clientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
      
        initComponents();
        confGrilla();
        cargarGrilla();
          bd = new ConeccionBD1();
           if (bd.estaConectado()) {
             JOptionPane.showMessageDialog(null, "Conectado con Exito", "Bienvenidos",JOptionPane.INFORMATION_MESSAGE);
             
            
    }else{
            JOptionPane.showMessageDialog(null,"Hubo un problema con la conexión ","Bienvenido",JOptionPane.INFORMATION_MESSAGE);
        }
        habilitraAgregar();
        inhabilitattxtAgregar();
        ocultarAvisosDeError();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        txtcodigoAgre = new javax.swing.JTextField();
        btnGenerarCodigo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtCedulaAgre = new javax.swing.JTextField();
        jlblErrorAgregarCI = new javax.swing.JLabel();
        jlblErrorAgregarNombres = new javax.swing.JLabel();
        jlblErrorAgregarApellidos = new javax.swing.JLabel();
        txtAgregarApellidos = new javax.swing.JTextField();
        txtAgregarNombres = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cmbAgregarSexo = new javax.swing.JComboBox();
        cmbAgregarTipo = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        txtAgregarDireccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtAgregarTelefono = new javax.swing.JTextField();
        txtAgregarCorreoElectronico = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnClienteAgregar = new javax.swing.JButton();
        btncancelarAgregar = new javax.swing.JButton();
        btnSalirAgregar = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        txtcodiActualizar = new javax.swing.JTextField();
        btnActualizarBuscarCliente = new javax.swing.JButton();
        jlblErrorActualizarDni = new javax.swing.JLabel();
        jlblErrorActualizarNombres = new javax.swing.JLabel();
        jlblErrorActualizarApellidos = new javax.swing.JLabel();
        txtActualizarCedula = new javax.swing.JTextField();
        txtActualizarNombres = new javax.swing.JTextField();
        txtActualizarApellidos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cmbActualizarSexo = new javax.swing.JComboBox();
        cmbActualizarTipo = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        txtActualizarDireccion = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtActualizarTelefono = new javax.swing.JTextField();
        txtActualizarCorreoElectronico = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnClienteActualizar = new javax.swing.JButton();
        btnCancelarActualizar = new javax.swing.JButton();
        btnActualizarSalir = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblclientes = new javax.swing.JTable();
        txtbuscar = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("CLIENTE - MANTENIMIENTO");

        jSeparator1.setBackground(new java.awt.Color(0, 102, 102));
        jSeparator1.setForeground(new java.awt.Color(0, 102, 102));
        jSeparator1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(255, 255, 0)));
        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTabbedPane2.setBackground(new java.awt.Color(0, 0, 0));
        jTabbedPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0))));
        jTabbedPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane2MouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Codigo del Cliente:");

        btnGenerarCodigo.setText("Generar Codigo");
        btnGenerarCodigo.setToolTipText("Para Generar Codigo");
        btnGenerarCodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGenerarCodigoMouseClicked(evt);
            }
        });
        btnGenerarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarCodigoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nro. Cedula");

        txtCedulaAgre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCedulaAgre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaAgreActionPerformed(evt);
            }
        });

        jlblErrorAgregarCI.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlblErrorAgregarCI.setForeground(new java.awt.Color(255, 0, 0));
        jlblErrorAgregarCI.setText("* Este campo no puede dejarse en blanco");

        jlblErrorAgregarNombres.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlblErrorAgregarNombres.setForeground(new java.awt.Color(255, 0, 0));
        jlblErrorAgregarNombres.setText("*Este campo no puede dejarse en blanco");

        jlblErrorAgregarApellidos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlblErrorAgregarApellidos.setForeground(new java.awt.Color(255, 0, 0));
        jlblErrorAgregarApellidos.setText("*Este campo no puede dejarse en blanco");

        txtAgregarApellidos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtAgregarApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgregarApellidosActionPerformed(evt);
            }
        });

        txtAgregarNombres.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtAgregarNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgregarNombresActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellidos:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombres:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Sexo:");

        cmbAgregarSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Femenino" }));
        cmbAgregarSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAgregarSexoActionPerformed(evt);
            }
        });

        cmbAgregarTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Común", "Socio" }));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Tipo:");

        txtAgregarDireccion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtAgregarDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgregarDireccionActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Dirección:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Telefono:");

        txtAgregarTelefono.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtAgregarTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgregarTelefonoActionPerformed(evt);
            }
        });

        txtAgregarCorreoElectronico.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtAgregarCorreoElectronico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgregarCorreoElectronicoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Correo electrónico:");

        btnClienteAgregar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnClienteAgregar.setText("Agregar");
        btnClienteAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteAgregarActionPerformed(evt);
            }
        });

        btncancelarAgregar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btncancelarAgregar.setText("Cancelar");
        btncancelarAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarAgregarActionPerformed(evt);
            }
        });

        btnSalirAgregar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSalirAgregar.setText("Salir");
        btnSalirAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirAgregarActionPerformed(evt);
            }
        });

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/icon_45.png"))); // NOI18N
        jLabel21.setText("jLabel20");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcodigoAgre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGenerarCodigo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(6, 6, 6)
                                        .addComponent(cmbAgregarSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(19, 19, 19)
                                        .addComponent(jLabel17)
                                        .addGap(10, 10, 10)
                                        .addComponent(cmbAgregarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtAgregarNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCedulaAgre, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtAgregarApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(jlblErrorAgregarCI))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlblErrorAgregarApellidos)
                                            .addComponent(jlblErrorAgregarNombres)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(4, 4, 4)
                                        .addComponent(txtAgregarCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(btnClienteAgregar)
                                            .addGap(11, 11, 11)
                                            .addComponent(btncancelarAgregar)
                                            .addGap(7, 7, 7)
                                            .addComponent(btnSalirAgregar))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(60, 60, 60)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(0, 0, 0)
                                                    .addComponent(txtAgregarDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel7)
                                                    .addGap(3, 3, 3)
                                                    .addComponent(txtAgregarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtcodigoAgre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCedulaAgre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblErrorAgregarCI, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAgregarNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jlblErrorAgregarNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAgregarApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jlblErrorAgregarApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(cmbAgregarSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(cmbAgregarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtAgregarDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtAgregarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txtAgregarCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnClienteAgregar)
                            .addComponent(btncancelarAgregar)
                            .addComponent(btnSalirAgregar))
                        .addGap(0, 48, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Agregar", jPanel2);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Codigo Cliente");

        txtcodiActualizar.setBorder(null);
        txtcodiActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodiActualizarActionPerformed(evt);
            }
        });

        btnActualizarBuscarCliente.setText("Buscar");
        btnActualizarBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarBuscarClienteActionPerformed(evt);
            }
        });

        jlblErrorActualizarDni.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlblErrorActualizarDni.setForeground(new java.awt.Color(255, 0, 0));
        jlblErrorActualizarDni.setText("* Este campo no puede dejarse en blanco");

        jlblErrorActualizarNombres.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlblErrorActualizarNombres.setForeground(new java.awt.Color(255, 0, 0));
        jlblErrorActualizarNombres.setText("*Este campo no puede dejarse en blanco");

        jlblErrorActualizarApellidos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlblErrorActualizarApellidos.setForeground(new java.awt.Color(255, 0, 0));
        jlblErrorActualizarApellidos.setText("*Este campo no puede dejarse en blanco");

        txtActualizarCedula.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtActualizarCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtActualizarCedulaActionPerformed(evt);
            }
        });

        txtActualizarNombres.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txtActualizarApellidos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nro. Cedula");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nombres:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Apellidos:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Sexo:");

        cmbActualizarSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Femenino" }));

        cmbActualizarTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Común", "Socio" }));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Tipo:");

        txtActualizarDireccion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Dirección:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Telefono:");

        txtActualizarTelefono.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txtActualizarCorreoElectronico.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Correo electrónico:");

        btnClienteActualizar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnClienteActualizar.setText("Actualizar");
        btnClienteActualizar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                btnClienteActualizarMouseDragged(evt);
            }
        });
        btnClienteActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActualizarActionPerformed(evt);
            }
        });

        btnCancelarActualizar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelarActualizar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancelarActualizar.setText("Cancelar");
        btnCancelarActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActualizarActionPerformed(evt);
            }
        });

        btnActualizarSalir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnActualizarSalir.setText("Salir");
        btnActualizarSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarSalirActionPerformed(evt);
            }
        });

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/icon_43.png"))); // NOI18N
        jLabel22.setText("jLabel20");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel23)
                        .addGap(11, 11, 11)
                        .addComponent(txtcodiActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5)
                        .addGap(40, 40, 40)
                        .addComponent(txtActualizarCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(btnActualizarBuscarCliente)
                        .addGap(15, 15, 15)
                        .addComponent(jlblErrorActualizarDni))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel10)
                        .addGap(53, 53, 53)
                        .addComponent(txtActualizarNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jlblErrorActualizarNombres))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel11)
                        .addGap(51, 51, 51)
                        .addComponent(txtActualizarApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jlblErrorActualizarApellidos))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel18)
                        .addGap(46, 46, 46)
                        .addComponent(cmbActualizarSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel19)
                        .addGap(10, 10, 10)
                        .addComponent(cmbActualizarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel12)
                        .addGap(51, 51, 51)
                        .addComponent(txtActualizarDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel13)
                                .addGap(53, 53, 53)
                                .addComponent(txtActualizarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(4, 4, 4)
                                .addComponent(txtActualizarCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btnClienteActualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCancelarActualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnActualizarSalir)))
                        .addGap(117, 117, 117)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel23))
                    .addComponent(txtcodiActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtActualizarCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarBuscarCliente)
                    .addComponent(jlblErrorActualizarDni, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtActualizarNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblErrorActualizarNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txtActualizarApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblErrorActualizarApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbActualizarSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(cmbActualizarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel12))
                    .addComponent(txtActualizarDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel13))
                            .addComponent(txtActualizarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(txtActualizarCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClienteActualizar)
                    .addComponent(btnCancelarActualizar)
                    .addComponent(btnActualizarSalir))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Actualizar", jPanel3);

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 0)), "Clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        tblclientes.setBackground(new java.awt.Color(0, 0, 0));
        tblclientes.setForeground(new java.awt.Color(255, 255, 255));
        tblclientes.setModel(modelo);
        jScrollPane1.setViewportView(tblclientes);

        txtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarActionPerformed(evt);
            }
        });

        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(207, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Editar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Clientes", jPanel6);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClienteAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteAgregarActionPerformed
            if (!existeCamposObligatoriosDeAgregarClienteEnBlanco()) {
                if (existeCedulaCliente()) {
                JOptionPane.showMessageDialog(null, "Ya existe un cliente registrado con el mismo número de Cedula: "
                        + "" + this.txtCedulaAgre.getText(), "Error", 2);
            } else {
                    agr= true;
           mod= false;
            agregar();
            vaciarTextoAgregar();
            habilitraAgregar();
            }
            }
   }//GEN-LAST:event_btnClienteAgregarActionPerformed

    private void btnSalirAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirAgregarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirAgregarActionPerformed

    private void btnGenerarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarCodigoActionPerformed
       gencod();
       inhhabilitraAgregar();
       habilitattxtAgregar();
       txtCedulaAgre.requestFocus();
    }//GEN-LAST:event_btnGenerarCodigoActionPerformed

    private void jTabbedPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane2MouseClicked
        habilitraActualizar();
        inhabilitattxtActualizar();
        ocultarAvisosDeError();
        cargarGrilla();
        txtActualizarCedula.requestFocus();
        txtActualizarCedula.setEditable(true);
    }//GEN-LAST:event_jTabbedPane2MouseClicked

    private void btnGenerarCodigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarCodigoMouseClicked
         // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerarCodigoMouseClicked

    private void btncancelarAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarAgregarActionPerformed
       vaciarTextoAgregar();
       inhabilitattxtAgregar();
       habilitraAgregar();
    }//GEN-LAST:event_btncancelarAgregarActionPerformed

    private void txtCedulaAgreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaAgreActionPerformed
        txtAgregarNombres.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaAgreActionPerformed

    private void txtAgregarNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgregarNombresActionPerformed
        txtAgregarApellidos.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgregarNombresActionPerformed

    private void txtAgregarApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgregarApellidosActionPerformed
        cmbAgregarSexo.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgregarApellidosActionPerformed

    private void cmbAgregarSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAgregarSexoActionPerformed
       txtAgregarDireccion.requestFocus(); // TODO add your handling code here:
    }//GEN-LAST:event_cmbAgregarSexoActionPerformed

    private void txtAgregarDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgregarDireccionActionPerformed
        txtAgregarTelefono.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgregarDireccionActionPerformed

    private void txtAgregarTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgregarTelefonoActionPerformed
        txtAgregarCorreoElectronico.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgregarTelefonoActionPerformed

    private void txtAgregarCorreoElectronicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgregarCorreoElectronicoActionPerformed
        btnClienteAgregar.requestFocus();
        btnClienteAgregar.doClick();        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgregarCorreoElectronicoActionPerformed

    private void txtcodiActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodiActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodiActualizarActionPerformed

    private void btnActualizarSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnActualizarSalirActionPerformed

    private void btnActualizarBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarBuscarClienteActionPerformed

        inhhabilitraActualizar();
        habilitattxtActualizar();
        buscar();



    }//GEN-LAST:event_btnActualizarBuscarClienteActionPerformed

    private void btnCancelarActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActualizarActionPerformed

        vaciarTextoActualizar();
        inhabilitattxtActualizar();
        habilitraActualizar();

    }//GEN-LAST:event_btnCancelarActualizarActionPerformed

    private void btnClienteActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActualizarActionPerformed
        ocultarAvisosDeErrorClienteActualizar();
        if (!existeCamposObligatoriosDeActualizarClienteEnBlanco()) {
            agr = false;
            mod = true;
            actualizar();
            vaciarTextoActualizar();
            habilitraActualizar();
        }
    }//GEN-LAST:event_btnClienteActualizarActionPerformed

    private void btnClienteActualizarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClienteActualizarMouseDragged

   }//GEN-LAST:event_btnClienteActualizarMouseDragged

    private void txtActualizarCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtActualizarCedulaActionPerformed
        btnActualizarBuscarCliente.requestFocus();
        btnActualizarBuscarCliente.doClick();
    }//GEN-LAST:event_txtActualizarCedulaActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        cargarGrilla();        // TODO add your handling code here:
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void txtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarActionPerformed
btnbuscar.requestFocus();
btnbuscar.doClick();
// TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
fila = tblclientes.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ningun registro");
        } else {

            int msj = JOptionPane.showConfirmDialog(null, "¿Realmente desea borrar el registro?", "Borrar", JOptionPane.YES_NO_OPTION);
            if (msj == JOptionPane.YES_OPTION) {
                borrar();
                limpiarGrilla();
                cargarGrilla();
                
            }
        }           // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        fila = tblclientes.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ningun registro");
        } else {
            jPanel6.setVisible(false);
            jPanel3.setVisible(true);
            jPanel5.setVisible(true);
            verDatos();
            txtcodiActualizar.setEnabled(false);
            btnActualizarBuscarCliente.setEnabled(false);
            btnCancelarActualizar.setEnabled(true);
            btnClienteActualizar.setEnabled(true);
            txtActualizarNombres.requestFocus();
            txtActualizarNombres.setEditable(true);
           
                    
            
            
                
            }
                   // TODO add your handling code here:
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
cargarGrilla(); // TODO add your handling code here:
}//GEN-LAST:event_jPanel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                Clientes dialog = new Clientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarBuscarCliente;
    private javax.swing.JButton btnActualizarSalir;
    private javax.swing.JButton btnCancelarActualizar;
    private javax.swing.JButton btnClienteActualizar;
    private javax.swing.JButton btnClienteAgregar;
    private javax.swing.JButton btnGenerarCodigo;
    private javax.swing.JButton btnSalirAgregar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btncancelarAgregar;
    private javax.swing.JComboBox cmbActualizarSexo;
    private javax.swing.JComboBox cmbActualizarTipo;
    private javax.swing.JComboBox cmbAgregarSexo;
    private javax.swing.JComboBox cmbAgregarTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel jlblErrorActualizarApellidos;
    private javax.swing.JLabel jlblErrorActualizarDni;
    private javax.swing.JLabel jlblErrorActualizarNombres;
    private javax.swing.JLabel jlblErrorAgregarApellidos;
    private javax.swing.JLabel jlblErrorAgregarCI;
    private javax.swing.JLabel jlblErrorAgregarNombres;
    private javax.swing.JTable tblclientes;
    private javax.swing.JTextField txtActualizarApellidos;
    private javax.swing.JTextField txtActualizarCedula;
    private javax.swing.JTextField txtActualizarCorreoElectronico;
    private javax.swing.JTextField txtActualizarDireccion;
    private javax.swing.JTextField txtActualizarNombres;
    private javax.swing.JTextField txtActualizarTelefono;
    private javax.swing.JTextField txtAgregarApellidos;
    private javax.swing.JTextField txtAgregarCorreoElectronico;
    private javax.swing.JTextField txtAgregarDireccion;
    private javax.swing.JTextField txtAgregarNombres;
    private javax.swing.JTextField txtAgregarTelefono;
    private javax.swing.JTextField txtCedulaAgre;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtcodiActualizar;
    private javax.swing.JTextField txtcodigoAgre;
    // End of variables declaration//GEN-END:variables

    private void habilitraAgregar(){
        btnGenerarCodigo.setEnabled(true);
        btnClienteAgregar.setEnabled(false);
        btnSalirAgregar.setEnabled(true);
        btncancelarAgregar.setEnabled(false);
            
    }
    private void inhhabilitraAgregar(){
        btnGenerarCodigo.setEnabled(false);
        btnClienteAgregar.setEnabled(true);
        btnSalirAgregar.setEnabled(true);
         btncancelarAgregar.setEnabled(true);
            
    }
    private void habilitattxtAgregar(){
        txtcodigoAgre.setEnabled(false);
        txtCedulaAgre.setEditable(true);
        txtAgregarNombres.setEditable(true);
        txtAgregarApellidos.setEditable(true);
        txtAgregarDireccion.setEditable(true);
        txtAgregarTelefono.setEditable(true);
        txtAgregarCorreoElectronico.setEditable(true);
    }
    private void inhabilitattxtAgregar(){
        txtcodigoAgre.setEnabled(false);
       txtCedulaAgre.setEditable(false);
        txtAgregarNombres.setEditable(false);
        txtAgregarApellidos.setEditable(false);
        txtAgregarDireccion.setEditable(false);
        txtAgregarTelefono.setEditable(false);
        txtAgregarCorreoElectronico.setEditable(false);
    }
    private void vaciarTextoAgregar(){
        txtcodigoAgre.setText("");
      txtCedulaAgre.setText("");
      txtAgregarNombres.setText("");
      txtAgregarApellidos.setText("");
      txtAgregarDireccion.setText("");
      txtAgregarTelefono.setText("");
      txtAgregarCorreoElectronico.setText("");    
    }
     private void habilitraActualizar(){
        btnActualizarBuscarCliente.setEnabled(true);
        btnClienteActualizar.setEnabled(false);
        btnActualizarSalir.setEnabled(true);
         btnCancelarActualizar.setEnabled(false);
            
    }
    private void inhhabilitraActualizar(){
        btnActualizarBuscarCliente.setEnabled(false);
        btnClienteActualizar.setEnabled(true);
        btnActualizarSalir.setEnabled(true);
         btnCancelarActualizar.setEnabled(true);
            
    }
    private void habilitattxtActualizar(){
        txtcodiActualizar.setEditable(true);
        txtActualizarCedula.setEditable(true);
        txtActualizarNombres.setEditable(true);
        txtActualizarApellidos.setEditable(true);
        txtActualizarDireccion.setEditable(true);
        txtActualizarTelefono.setEditable(true);
        txtActualizarCorreoElectronico.setEditable(true);
    }
    private void inhabilitattxtActualizar(){
        txtcodiActualizar.setEditable(false);
        txtActualizarCedula.setEditable(false);
        txtActualizarNombres.setEditable(false);
        txtActualizarApellidos.setEditable(false);
        txtActualizarDireccion.setEditable(false);
        txtActualizarTelefono.setEditable(false);
        txtActualizarCorreoElectronico.setEditable(false);
    }
    private void vaciarTextoActualizar(){
        txtcodiActualizar.setText("");
      txtActualizarCedula.setText("");
      txtActualizarNombres.setText("");
      txtActualizarApellidos.setText("");
      txtActualizarDireccion.setText("");
      txtActualizarTelefono.setText("");
      txtActualizarCorreoElectronico.setText("");    
    }
     private void ocultarAvisosDeErrorClienteAgregar() {
        this.jlblErrorAgregarCI.setVisible(false);
        this.jlblErrorAgregarNombres.setVisible(false);
        this.jlblErrorAgregarApellidos.setVisible(false);
    }

    private void ocultarAvisosDeErrorClienteActualizar() {
        this.jlblErrorActualizarDni.setVisible(false);
        this.jlblErrorActualizarNombres.setVisible(false);
        this.jlblErrorActualizarApellidos.setVisible(false);
    }
    
   private void gencod() {
        try{
             ConeccionBD1 z = new ConeccionBD1();
             Connection cn = z.conectar();
           
            Statement stmt = cn.createStatement();
            rs = stmt.executeQuery("SELECT IFNULL(MAX(idClientes),0)+1 AS codigo FROM clientes");
            rs.next();
            txtcodigoAgre.setText(rs.getString("codigo"));
        }catch (SQLException exceptionSql){
            JOptionPane.showMessageDialog(null, exceptionSql.getMessage(), "Error de Conexion con la Base de Datos", JOptionPane.ERROR_MESSAGE);
		System.exit(0);
        }
    } 
    private void agregar(){
       
        try {
            if (agr==true){
        JOptionPane optionPane=new JOptionPane();
                     Object[] opciones =  {"Si","No"};
                      int ret=JOptionPane.showOptionDialog(null,"Desea guardar?","pregunta",JOptionPane.YES_NO_OPTION,
                           JOptionPane.QUESTION_MESSAGE,null,opciones,opciones[0]);
                       if(ret==JOptionPane.YES_OPTION)
                    if(bd.insertarRegistro("clientes","idClientes, CIclientes,NombreCliente,ApellidoCliente,DireccionCliente, "
                            + "TelefonoCliente,CorreoCliente,tipoCliente,sexoCliente "
                            + "","'"+ txtcodigoAgre.getText()+"','"+
                           txtCedulaAgre.getText()+"','"+ txtAgregarNombres.getText()+"','"+ txtAgregarApellidos.getText()+"', "
                            + "'"+ txtAgregarDireccion.getText()+"','"+ txtAgregarTelefono.getText()+"','"+ txtAgregarCorreoElectronico.getText()+"', "
                            + "'"+ cmbAgregarTipo.getSelectedItem()+"', '"+ cmbAgregarSexo.getSelectedItem()+"'")){
                       error =false;
            
                rs.close();
                    }
            }
            } catch (SQLException ex) {
                Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    
    private void actualizar(){
      try {
        ConeccionBD1 z = new ConeccionBD1();
             Connection cn = z.conectar();
             Statement stmt = cn.createStatement();
             
       String update = "UPDATE clientes " + "SET "
                        + "CIclientes='" + txtActualizarCedula.getText() + "', "
                        + "NombreCliente='" + txtActualizarNombres.getText() + "', "
                        + "ApellidoCliente='" + txtActualizarApellidos.getText() + "', "
                        + "DireccionCliente='" + txtActualizarDireccion.getText() + "', "
                        + "TelefonoCliente='" + txtActualizarTelefono.getText() + "', "
                        + "CorreoCliente='" + txtActualizarCorreoElectronico.getText() + "' ,"
                        + "tipoCliente='" + cmbActualizarTipo.getSelectedItem() + "' ,"
                        + "sexoCliente='" + cmbActualizarSexo.getSelectedItem()+ "' "
                        + "WHERE idClientes='" + txtcodiActualizar.getText() + "';";
            JOptionPane.showMessageDialog(null, "Se ha Modificado con exito", "Felicitaciones",JOptionPane.INFORMATION_MESSAGE);
                stmt.executeUpdate(update);
                stmt.close();
                cn.close();
              } catch (SQLException ex) {
                Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
            }  
                        
                       
    }
    private void ocultarAvisosDeError() {
        this.jlblErrorAgregarCI.setVisible(false);
        this.jlblErrorAgregarNombres.setVisible(false);
        this.jlblErrorAgregarApellidos.setVisible(false);

        this.jlblErrorActualizarDni.setVisible(false);
        this.jlblErrorActualizarNombres.setVisible(false);
        this.jlblErrorActualizarApellidos.setVisible(false);



    }
   private boolean existeCamposObligatoriosDeAgregarClienteEnBlanco() {
        boolean existe = false;
        if (this.txtCedulaAgre.getText().length() == 0) {
            this.jlblErrorAgregarCI.setVisible(true);
            existe = true;
        }
        if (this.txtAgregarNombres.getText().length() == 0) {
            this.jlblErrorAgregarNombres.setVisible(true);
            existe = true;
        }
        if (this.txtAgregarApellidos.getText().length() == 0) {
            this.jlblErrorAgregarApellidos.setVisible(true);
            existe = true;
        }
        return existe;
    }

    private boolean existeCamposObligatoriosDeActualizarClienteEnBlanco() {
        boolean existe = false;
        if (this.txtActualizarCedula.getText().length() == 0) {
            this.jlblErrorActualizarDni.setVisible(true);
            existe = true;
        }
        if (this.txtActualizarNombres.getText().length() == 0) {
            this.jlblErrorActualizarNombres.setVisible(true);
            existe = true;
        }
        if (this.txtActualizarApellidos.getText().length() == 0) {
            this.jlblErrorActualizarApellidos.setVisible(true);
            existe = true;
        }
        return existe;
    }
    private boolean existeCedulaCliente() {
        boolean existe = false;
        if (bd.existeCedulaCliente(this.txtCedulaAgre.getText())) {
            existe = true;
        }
        return existe;
    }
    private void buscar(){
        if(this.txtActualizarCedula.getText().length()==0){
        
    
        JOptionPane.showMessageDialog(null,"Por Favor Ingrese el numero de cedula..","Aviso", JOptionPane.INFORMATION_MESSAGE);
		
                vaciarTextoActualizar();
                habilitraActualizar();
                txtActualizarCedula.requestFocus();
                txtActualizarCedula.setEditable(true);
        }else{
            String CI = this.txtActualizarCedula.getText();
            cliente = bd.obtenerClientePorCI(CI);
             this.txtcodiActualizar.setText(cliente.getid().toString());
            this.txtActualizarCedula.setText(cliente.getCI());
           
            this.txtActualizarNombres.setText(cliente.getNombres());
            this.txtActualizarApellidos.setText(cliente.getApellidos());
            this.cmbActualizarSexo.setSelectedItem(cliente.getSexo());
            this.cmbActualizarTipo.setSelectedItem(cliente.getTipo());
            this.txtActualizarDireccion.setText(cliente.getDireccion());
            this.txtActualizarTelefono.setText(cliente.getTelefono());
            this.txtActualizarCorreoElectronico.setText(cliente.getCorreo());
        }
                
    
   
}
    private void confGrilla(){
        modelo.addColumn("Codigo"); 
        modelo.addColumn("CI.Nro");
        modelo.addColumn("Nombre"); 
        modelo.addColumn("Apellido");
        modelo.addColumn("Tipo"); 
        modelo.addColumn("Telefono");
    
    }
    private void cargarGrilla(){
        modelo.setRowCount(0);
        try {
            String sql = "select idClientes, CIclientes,NombreCliente,ApellidoCliente,tipoCliente,"
                    + "telefonoCliente  from clientes";
            if(txtbuscar.getText().trim().length() > 0)
                 sql = sql+" where concat (CIclientes,' ', NombreCliente, ' ', ApellidoCliente,' ',tipoCliente) like '%"+txtbuscar.getText()+"%'";

            sql = sql+" order by idClientes";
            String[] datos = new String[6];
            ConeccionBD1 z = new ConeccionBD1();
             Connection cn = z.conectar();
             Statement stmt = cn.createStatement();
             rs = stmt.executeQuery(sql);
            while(rs.next()){
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4] = rs.getString(5);
               datos[5] = rs.getString(6); 
                
                modelo.addRow(datos);

            }
        } catch (SQLException ex) {
            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
     
     private void borrar(){
        try {
            ConeccionBD1 z = new ConeccionBD1();
             Connection cn = z.conectar(); 
             fila = this.tblclientes.getSelectedRow();
            Object cod_cli=this.tblclientes.getValueAt(fila,0);
            String sql = "DELETE FROM clientes WHERE idClientes = "+cod_cli;
            Statement stmt = cn.createStatement();
            stmt.executeUpdate(sql);
        } catch (SQLException ex) {
            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
      private void limpiarGrilla() {   
         while (modelo.getRowCount() > 0)
             modelo.removeRow(0);
     }
       private void verDatos(){
         String cod = "",ci  = "",nom="",ape="",sex="",tip="",dir="", tel="",ema=""; 
          fila = tblclientes.getSelectedRow();
         int cod_ma=Integer.parseInt(modelo.getValueAt(fila,0).toString());
         ConeccionBD1 z =new ConeccionBD1();
         Connection cn = z.conectar();
         String sql = "SELECT * From clientes "+
                 " WHERE idClientes= "+ cod_ma;
       try {
                 Statement st = cn.createStatement();
                 rs = st.executeQuery(sql);
                while (rs.next())
                {
                 
                cod = rs.getString("idClientes");
                ci= rs.getString("CIclientes");
                nom = rs.getString("NombreCliente");
                ape = rs.getString("ApellidoCliente");
                sex = rs.getString("sexoCliente");
                tip = rs.getString("tipoCliente");
                dir= rs.getString("DireccionCliente");
                tel= rs.getString("TelefonoCliente");
                ema= rs.getString("CorreoCliente");
               
               
       
            }
            txtcodiActualizar.setText(cod);
            txtActualizarCedula.setText(ci);
            txtActualizarNombres.setText(nom);
            txtActualizarApellidos.setText(ape);
            txtActualizarDireccion.setText(dir);
            txtActualizarTelefono.setText(tel);
            txtActualizarCorreoElectronico.setText(ema);
            cmbActualizarSexo.setSelectedItem(sex);
            cmbActualizarTipo.setSelectedItem(tip);
            
            
            
                
        }
        
        catch (SQLException ex) 
        {
            JOptionPane.showMessageDialog(null, ex);
        }
        
     }
    
}
