/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Programas;

import Clases.CatalogoPeli;
import Clases.ConeccionBD1;
import Modelo.Pelicula;

import java.util.ArrayList;
import Modelo.Ejemplar;

import javax.swing.JOptionPane;
import Modelo.Cliente;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;


/**
 *
 * @author Ruben
 */
public class Ejemplares extends javax.swing.JDialog {
private ConeccionBD1 bd;
private Cliente cliente;
private Pelicula pelicula;
private ArrayList<Ejemplar> listaEjemplaresPorPelicula;
private Ejemplar ejemplar;
private ResultSet rs;
    /**
     * Creates new form Ejemplares
     */
    public Ejemplares(java.awt.Frame parent, boolean modal) {
        
        initComponents();
        bd = new ConeccionBD1();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblPeliculaEjemplares = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel71 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtAgregarStockCantidadAAgregar = new javax.swing.JTextField();
        cmbAgregarStockFormato = new javax.swing.JComboBox();
        btnAgregarStock = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtPeliculaGenero = new javax.swing.JTextField();
        txtPeliculaTitulo = new javax.swing.JTextField();
        jbtnVerCatalogoPeliculas = new javax.swing.JButton();
        btnVerEjemplaresPorPelicula = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        txtPeliculaStock = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtPeliculaStockDVD = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtPeliculaStockBluRay = new javax.swing.JTextField();
        jlblPeliculaImagen = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("AGREGAR STOCK");

        jSeparator1.setForeground(new java.awt.Color(0, 102, 102));
        jSeparator1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(255, 255, 0)));
        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)), "Ejemplares", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(255, 204, 0)));

        jtblPeliculaEjemplares.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nro", "Código", "Formato", "PrecioAlquiler", "PrecioVenta", "Estado"
            }
        ));
        jtblPeliculaEjemplares.setEnabled(false);
        jtblPeliculaEjemplares.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblPeliculaEjemplaresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblPeliculaEjemplares);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)), "Agregar Stock", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(255, 204, 0)));

        jLabel71.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(255, 255, 255));
        jLabel71.setText("Tipo de Formato:");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Cantidad de Ejemplares a agregar:");

        txtAgregarStockCantidadAAgregar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        cmbAgregarStockFormato.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbAgregarStockFormato.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DVD", "Blu-Ray" }));

        btnAgregarStock.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAgregarStock.setText("Agregar Stock");
        btnAgregarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarStockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel71))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregarStock)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cmbAgregarStockFormato, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtAgregarStockCantidadAAgregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtAgregarStockCantidadAAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel71)
                    .addComponent(cmbAgregarStockFormato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btnAgregarStock)
                .addGap(0, 43, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Genero:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Título:");

        txtPeliculaGenero.setEditable(false);
        txtPeliculaGenero.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txtPeliculaTitulo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jbtnVerCatalogoPeliculas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnVerCatalogoPeliculas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/catalogoPeliculas.png"))); // NOI18N
        jbtnVerCatalogoPeliculas.setActionCommand("Ver Ejemplares");
        jbtnVerCatalogoPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVerCatalogoPeliculasActionPerformed(evt);
            }
        });

        btnVerEjemplaresPorPelicula.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnVerEjemplaresPorPelicula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/verEjemplares.jpg"))); // NOI18N
        btnVerEjemplaresPorPelicula.setText("Ejemplares");
        btnVerEjemplaresPorPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerEjemplaresPorPeliculaActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Stock:");

        txtPeliculaStock.setEditable(false);
        txtPeliculaStock.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Stock DVD:");

        txtPeliculaStockDVD.setEditable(false);
        txtPeliculaStockDVD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Stock Blu-Ray:");

        txtPeliculaStockBluRay.setEditable(false);
        txtPeliculaStockBluRay.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jlblPeliculaImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/6.jpg"))); // NOI18N
        jlblPeliculaImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 51)));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel25)
                        .addGap(11, 11, 11)
                        .addComponent(txtPeliculaStock, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel19)
                        .addGap(11, 11, 11)
                        .addComponent(txtPeliculaStockDVD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel21)
                        .addGap(10, 10, 10)
                        .addComponent(txtPeliculaStockBluRay, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlblPeliculaImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPeliculaGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(210, 210, 210)
                                .addComponent(jbtnVerCatalogoPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(1, 1, 1)
                                .addComponent(txtPeliculaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btnVerEjemplaresPorPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbtnVerCatalogoPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPeliculaGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(txtPeliculaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVerEjemplaresPorPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(txtPeliculaStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(txtPeliculaStockDVD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(txtPeliculaStockBluRay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlblPeliculaImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnVerCatalogoPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVerCatalogoPeliculasActionPerformed
      //aqui definimos una matriz de tipo jTexfield y el numero de columnas
        JTextField[] tfParam = new JTextField[2];
        // se le asigna donde va a mostrar el valor de cada columna
        tfParam[1] = this.txtPeliculaTitulo;
        
        

        // instanciamos nuestra clase ventanaBuscar que se encuentra en el paquete clases
        // creamos la consulta con select de acuerdo a lo que queremos mostrar
        // en nuestra VentanaBuscar 
         CatalogoPeli pp = new CatalogoPeli("select Codigo, Pelicula from vistapelicula where Pelicula like ",
                new String[]{"CODIGO", "PELICULA"}, 2, tfParam);
        // Colocamos un titulo en nuestra VentanaBuscar con el comando setTitle
        // en esta linea hacemos que sea visible nuestra ventana Buscar
        // con el comando setVisible
        pp.setVisible(true);
        // habilitamos el txtcantidad
        
      
       // CatalagoPelicula vcp = new CatalagoPelicula(null, rootPaneCheckingEnabled);
        //vcp.setVisible(true);
        //vcp.setDefaultCloseOperation(2);
    }//GEN-LAST:event_jbtnVerCatalogoPeliculasActionPerformed

    private void btnVerEjemplaresPorPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerEjemplaresPorPeliculaActionPerformed
        String tituloPelicula= this.txtPeliculaTitulo.getText().trim().toUpperCase();
        if (existeTituloPelicula(tituloPelicula)){
            pelicula = bd.obtenerPeliculaPorTitulo(tituloPelicula);
            listaEjemplaresPorPelicula = bd.obtenerEjemplaresPorPeliculaConEstadoLibre(pelicula);
            int stockDVD = 0;
            int stockBluRay = 0;
            this.txtPeliculaGenero.setText(pelicula.getGenero().getDescripcion());
            this.txtPeliculaTitulo.setText(tituloPelicula);
            this.jlblPeliculaImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/"
                    + "" + this.pelicula.getId() + ".jpg")));
             for (int i = 0; i < this.listaEjemplaresPorPelicula.size(); i++) {
                
                this.jtblPeliculaEjemplares.setValueAt((i + 1), i, 0);
                this.jtblPeliculaEjemplares.setValueAt(this.listaEjemplaresPorPelicula.get(i).getId(), i, 1);
                this.jtblPeliculaEjemplares.setValueAt(this.listaEjemplaresPorPelicula.get(i).getFormato(), i, 2);
                this.jtblPeliculaEjemplares.setValueAt(this.listaEjemplaresPorPelicula.get(i).getPrecioAlquiler(), i, 3);
                this.jtblPeliculaEjemplares.setValueAt(this.listaEjemplaresPorPelicula.get(i).getPrecioVenta(), i,4);
                this.jtblPeliculaEjemplares.setValueAt(this.listaEjemplaresPorPelicula.get(i).getEstado(), i, 5);
                
                if (listaEjemplaresPorPelicula.get(i).getFormato().equalsIgnoreCase("DVD")) {
                    stockDVD++;
                }
                
                if (listaEjemplaresPorPelicula.get(i).getFormato().equalsIgnoreCase("Blu-Ray")) {
                    stockBluRay++;
                }
                
                
            }
            this.txtPeliculaStock.setText("" + (stockDVD + stockBluRay));
            this.txtPeliculaStockDVD.setText("" + stockDVD);
            this.txtPeliculaStockBluRay.setText("" + stockBluRay);
        } else {
            JOptionPane.showMessageDialog(null, "La Pelicula :" + tituloPelicula + " no existe!");
        
            
            
        
            
            
            
       }
        
    }//GEN-LAST:event_btnVerEjemplaresPorPeliculaActionPerformed

    private void btnAgregarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarStockActionPerformed
        int cantidadAgregar = Integer.parseInt(this.txtAgregarStockCantidadAAgregar.getText());
        for (int i = 0; i < cantidadAgregar; i++ ) {
            System.out.println("entro-antes");
            if (this.jtblPeliculaEjemplares.getValueAt(i, 0) != null) {
                System.out.println("entro");

               
               // String formato = (String) this.jtblPeliculaEjemplares.getValueAt(i, 1);
//                Double precioalquiler = (Double) this.jtblPeliculaEjemplares.getValueAt(i, 3);
                String estado = (String) this.jtblPeliculaEjemplares.getValueAt(i, 5);
        //        Double precioventa = (Double) this.jtblPeliculaEjemplares.getValueAt(i, 4);
               
        String idpelicula= this.pelicula.getId();

       if (this.cmbAgregarStockFormato.getSelectedItem().toString().equalsIgnoreCase("DVD")) {
         bd.insertarRegistro("ejemplar", "idPelicula,formatoejemplar,precioAlquilerEjemplar,PrecioVentaEjemplar,estadoejemplar ",
                 "'" + idpelicula + "','"
                    + cmbAgregarStockFormato.getSelectedItem()+ "',10000,40000,'" + estado + "'");
                        System.out.println("blu-ray");
               
            } else {
           
           bd.insertarRegistro("ejemplar", "idPelicula,formatoejemplar,precioAlquilerEjemplar,PrecioVentaEjemplar,estadoejemplar ",
                 "'" + idpelicula + "','"
                    + cmbAgregarStockFormato.getSelectedItem()+ "',10000,40000,'" + estado + "'");
           System.out.println("blu-ray");
       }
            }
        }
         ;
        int Stock = Integer.parseInt(this.txtPeliculaStock.getText());
        int total= cantidadAgregar + Stock;
        String idpelicula= this.pelicula.getId();
                
         bd.actualizarRegistro("pelicula", "Stock_Pelicula=" + total + "",
                            "idPelicula=" + idpelicula);
        
        JOptionPane.showMessageDialog(null, "El nuevo stock ha sido añadido con exito!");
        limpiar(); 
    limpiartabla();
    }//GEN-LAST:event_btnAgregarStockActionPerformed

    private void jtblPeliculaEjemplaresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblPeliculaEjemplaresMouseClicked
        int i = this.jtblPeliculaEjemplares.getSelectedRow();


    }//GEN-LAST:event_jtblPeliculaEjemplaresMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    limpiar(); 
    limpiartabla();
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   dispose();     // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejemplares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejemplares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejemplares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejemplares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                Ejemplares dialog = new Ejemplares(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarStock;
    private javax.swing.JButton btnVerEjemplaresPorPelicula;
    private javax.swing.JComboBox cmbAgregarStockFormato;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbtnVerCatalogoPeliculas;
    private javax.swing.JLabel jlblPeliculaImagen;
    private javax.swing.JTable jtblPeliculaEjemplares;
    private javax.swing.JTextField txtAgregarStockCantidadAAgregar;
    private javax.swing.JTextField txtPeliculaGenero;
    private javax.swing.JTextField txtPeliculaStock;
    private javax.swing.JTextField txtPeliculaStockBluRay;
    private javax.swing.JTextField txtPeliculaStockDVD;
    private javax.swing.JTextField txtPeliculaTitulo;
    // End of variables declaration//GEN-END:variables

    private boolean existeTituloPelicula(String tituloPelicula) {
            return bd.existeTituloPelicula(tituloPelicula);
    }
    
    private void limpiar(){
        txtAgregarStockCantidadAAgregar.setText("");
        txtPeliculaGenero.setText("");
        txtPeliculaStockBluRay.setText("");
        txtPeliculaTitulo.setText("");
        txtPeliculaStock.setText("");
        txtPeliculaStockDVD.setText("");
        cmbAgregarStockFormato.setSelectedItem(null);
        this.listaEjemplaresPorPelicula.clear();
        
    }
    private void limpiartabla(){
        for (int e = 0; e < this.jtblPeliculaEjemplares.getRowCount(); e++) {
            this.jtblPeliculaEjemplares.setValueAt("", e, 0);
            this.jtblPeliculaEjemplares.setValueAt("", e, 1);
            this.jtblPeliculaEjemplares.setValueAt("", e, 2);
            this.jtblPeliculaEjemplares.setValueAt("", e, 3);
            this.jtblPeliculaEjemplares.setValueAt("", e, 4);
            this.jtblPeliculaEjemplares.setValueAt("", e, 5);
            
        }
    }
    private void gencod() {
        try{
             ConeccionBD1 z = new ConeccionBD1();
             Connection cn = z.conectar();
           
            Statement stmt = cn.createStatement();
            rs = stmt.executeQuery("SELECT IFNULL(MAX(idPelicula),0)+1 AS codigo FROM pelicula");
            rs.next();
            //.setText(rs.getString("codigo"));
        }catch (SQLException exceptionSql){
            JOptionPane.showMessageDialog(null, exceptionSql.getMessage(), "Error de Conexion con la Base de Datos", JOptionPane.ERROR_MESSAGE);
		System.exit(0);
        }
    } 

}
