/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Programas;

import Clases.ConeccionBD1;
import Modelo.Cliente;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ruben
 */
public class Peliculas extends javax.swing.JDialog {
 DefaultTableModel modelo = new DefaultTableModel();
 private ConeccionBD1 bd;
  private ResultSet rs;
   private boolean error;
   private Cliente cliente;
   boolean agr, mod, bor = false;
    int fila = 0;
    private static String gencod, gen,gencodmo,genmod;
    String codGenero,codGeneroModi;
    /**
     * Creates new form Pelicula
     */
    public Peliculas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        confGrilla();
        cargarGrilla();
         
          bd = new ConeccionBD1();
           bd.estaConectado();
           bd.cargarCombo("select *from genero ", cmbgeneroagre);
           
           
        habilitraAgregar();
        txtcodigomodi.setEnabled(false);
        inhabilitattxtAgregar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtcodigoAgre = new javax.swing.JTextField();
        btnGenerarCodigo = new javax.swing.JButton();
        txtpeliagre = new javax.swing.JTextField();
        txtpaisagre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtduracionare = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtteleAgre = new javax.swing.JTextField();
        btnPeliAgregar = new javax.swing.JButton();
        btncancelarAgregar = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        cmbgeneroagre = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtactoresagre = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txasinopsisagre = new javax.swing.JTextArea();
        btnSalirAgregar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblpeli = new javax.swing.JTable();
        txtbuscar = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        jlblImagenCatalogoPeliculas = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jlblPeliculaTituloGrande = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtxaPeliculaActores = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        txtduracionmodi = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtcodigomodi = new javax.swing.JTextField();
        cmbgeneromodi = new javax.swing.JComboBox();
        txttitulomodi = new javax.swing.JTextField();
        txtpaismodi = new javax.swing.JTextField();
        txtdirectormodi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxaPeliculaSinopsis = new javax.swing.JTextArea();
        jLabel29 = new javax.swing.JLabel();
        BtnModificar = new javax.swing.JButton();
        BtnBorrar = new javax.swing.JButton();
        btnCAncelar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnguardarmodi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Pelicula - MANTENIMIENTO");

        jSeparator1.setBackground(new java.awt.Color(0, 102, 102));
        jSeparator1.setForeground(new java.awt.Color(0, 102, 102));
        jSeparator1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(255, 255, 0)));
        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTabbedPane2.setBackground(new java.awt.Color(0, 0, 0));
        jTabbedPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0))));
        jTabbedPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane2MouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        btnGenerarCodigo.setText("Generar Codigo");
        btnGenerarCodigo.setToolTipText("Para Generar Codigo");
        btnGenerarCodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGenerarCodigoMouseClicked(evt);
            }
        });
        btnGenerarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarCodigoActionPerformed(evt);
            }
        });

        txtpeliagre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtpeliagre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpeliagreActionPerformed(evt);
            }
        });

        txtpaisagre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtpaisagre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpaisagreActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Genero:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pais:");

        txtduracionare.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtduracionare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtduracionareActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Duraccion:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Director:");

        txtteleAgre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtteleAgre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtteleAgreActionPerformed(evt);
            }
        });

        btnPeliAgregar.setBackground(new java.awt.Color(255, 0, 51));
        btnPeliAgregar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnPeliAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/PNG/Load.png"))); // NOI18N
        btnPeliAgregar.setText("Guardar");
        btnPeliAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeliAgregarActionPerformed(evt);
            }
        });

        btncancelarAgregar.setBackground(new java.awt.Color(255, 51, 0));
        btncancelarAgregar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btncancelarAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/PNG/PNG-24/Delete.png"))); // NOI18N
        btncancelarAgregar.setText("Cancelar");
        btncancelarAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarAgregarActionPerformed(evt);
            }
        });

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/icon_45.png"))); // NOI18N
        jLabel21.setText("jLabel20");

        cmbgeneroagre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbgeneroagreActionPerformed(evt);
            }
        });
        cmbgeneroagre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbgeneroagreKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Titulo Pelicula:");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Codigo Pelicula:");

        jScrollPane2.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 0)), "Actores"));

        txtactoresagre.setColumns(20);
        txtactoresagre.setRows(5);
        jScrollPane2.setViewportView(txtactoresagre);

        jScrollPane3.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 0)), "Sinopsis"));

        txasinopsisagre.setColumns(20);
        txasinopsisagre.setRows(5);
        jScrollPane3.setViewportView(txasinopsisagre);

        btnSalirAgregar.setBackground(new java.awt.Color(255, 51, 0));
        btnSalirAgregar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSalirAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/PNG/PNG-32/Exit.png"))); // NOI18N
        btnSalirAgregar.setText("Salir");
        btnSalirAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcodigoAgre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGenerarCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(291, 291, 291))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtpeliagre, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 305, Short.MAX_VALUE))
                            .addComponent(jScrollPane3))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtduracionare, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpaisagre, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtteleAgre, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbgeneroagre, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(168, 168, 168)
                        .addComponent(btnPeliAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btncancelarAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalirAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGenerarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcodigoAgre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtpeliagre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtpaisagre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtduracionare, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtteleAgre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbgeneroagre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(222, 222, 222)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnPeliAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btncancelarAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSalirAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Agregar", jPanel2);

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), "Peliculas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(255, 153, 0)));

        jPanel11.setBackground(new java.awt.Color(0, 0, 0));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)), "Tabla", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(255, 102, 0)));

        tblpeli.setModel(modelo);
        tblpeli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpeliMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblpeli);

        txtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarActionPerformed(evt);
            }
        });

        btnbuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/PNG/PNG-24/Search.png"))); // NOI18N
        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnbuscar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jlblImagenCatalogoPeliculas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/AF0481.jpg"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("DETALLE DE LA PELÍCULA");

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/estrella.png"))); // NOI18N
        jLabel26.setText("jLabel1");

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)), "Detalle", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(255, 102, 0)));

        jlblPeliculaTituloGrande.setBackground(new java.awt.Color(0, 0, 0));
        jlblPeliculaTituloGrande.setEditable(false);
        jlblPeliculaTituloGrande.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblPeliculaTituloGrande.setForeground(new java.awt.Color(255, 255, 0));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Título      :");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Género    :");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Duración :");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("País         : ");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Director   :");

        jtxaPeliculaActores.setBackground(new java.awt.Color(0, 0, 0));
        jtxaPeliculaActores.setColumns(20);
        jtxaPeliculaActores.setForeground(new java.awt.Color(255, 255, 255));
        jtxaPeliculaActores.setRows(5);
        jScrollPane4.setViewportView(jtxaPeliculaActores);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Actores   :");

        txtduracionmodi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtduracionmodiActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Codigo    :");

        cmbgeneromodi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbgeneromodiMouseClicked(evt);
            }
        });
        cmbgeneromodi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbgeneromodiActionPerformed(evt);
            }
        });
        cmbgeneromodi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbgeneromodiKeyPressed(evt);
            }
        });

        txttitulomodi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttitulomodiActionPerformed(evt);
            }
        });

        txtpaismodi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpaismodiActionPerformed(evt);
            }
        });

        txtdirectormodi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdirectormodiActionPerformed(evt);
            }
        });

        jtxaPeliculaSinopsis.setBackground(new java.awt.Color(0, 0, 0));
        jtxaPeliculaSinopsis.setColumns(20);
        jtxaPeliculaSinopsis.setForeground(new java.awt.Color(255, 255, 255));
        jtxaPeliculaSinopsis.setRows(5);
        jScrollPane1.setViewportView(jtxaPeliculaSinopsis);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Sinopsis   :");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblPeliculaTituloGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txttitulomodi, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbgeneromodi, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcodigomodi, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtduracionmodi, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtpaismodi, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtdirectormodi, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(14, 14, 14))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jlblPeliculaTituloGrande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtcodigomodi))
                .addGap(8, 8, 8)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txttitulomodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cmbgeneromodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(txtduracionmodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpaismodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtdirectormodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel10)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel29))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        BtnModificar.setBackground(new java.awt.Color(255, 51, 0));
        BtnModificar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/PNG/PNG-24/Modify.png"))); // NOI18N
        BtnModificar.setText("Modificar");
        BtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarActionPerformed(evt);
            }
        });

        BtnBorrar.setBackground(new java.awt.Color(255, 51, 51));
        BtnBorrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/PNG/PNG-24/Delete.png"))); // NOI18N
        BtnBorrar.setText("Borrar");
        BtnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorrarActionPerformed(evt);
            }
        });

        btnCAncelar.setBackground(new java.awt.Color(255, 51, 51));
        btnCAncelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCAncelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Imagenes/icon_30.png"))); // NOI18N
        btnCAncelar.setText("Cancelar");
        btnCAncelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCAncelarActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(255, 51, 51));
        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/PNG/PNG-24/Exit.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnguardarmodi.setBackground(new java.awt.Color(255, 51, 51));
        btnguardarmodi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnguardarmodi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/PNG/PNG-24/Save.png"))); // NOI18N
        btnguardarmodi.setText("Guardar");
        btnguardarmodi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarmodiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jlblImagenCatalogoPeliculas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(BtnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnguardarmodi, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCAncelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BtnBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCAncelar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnguardarmodi)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblImagenCatalogoPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel28)
                .addGap(291, 291, 291))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel28)
                        .addGap(405, 405, 405))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 1311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Detalle", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane2MouseClicked
      //  habilitraActualizar();
        //inhabilitattxtActualizar();
        //ocultarAvisosDeError();
        bd.cargarCombo("select *from genero ", cmbgeneromodi);
        cargarGrilla();
        inhabilitattxtActualizar();
         BtnBorrar.setEnabled(false);
        btnguardarmodi.setEnabled(false);
        BtnModificar.setEnabled(false);
        btnbuscar.setEnabled(true);
        btnSalir.setEnabled(false);
        btnCAncelar.setEnabled(false);
        
        txtbuscar.requestFocus();
        
        //txtActualizarCedula.requestFocus();
        //txtActualizarCedula.setEditable(true);
    }//GEN-LAST:event_jTabbedPane2MouseClicked

    private void btnSalirAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirAgregarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirAgregarActionPerformed

    private void btncancelarAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarAgregarActionPerformed
        vaciarTextoAgregar();
        inhabilitattxtAgregar();
        habilitraAgregar();
    }//GEN-LAST:event_btncancelarAgregarActionPerformed

    private void btnPeliAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeliAgregarActionPerformed
       
                agr = true;
                mod = false;
                agregar();
                vaciarTextoAgregar();
                habilitraAgregar();
            
        
    }//GEN-LAST:event_btnPeliAgregarActionPerformed

    private void txtteleAgreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtteleAgreActionPerformed
        cmbgeneroagre.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtteleAgreActionPerformed

    private void txtduracionareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtduracionareActionPerformed
        txtdirectormodi.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtduracionareActionPerformed

    private void txtpaisagreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpaisagreActionPerformed
        txtduracionare.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtpaisagreActionPerformed

    private void txtpeliagreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpeliagreActionPerformed
        txtpaisagre.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtpeliagreActionPerformed

    private void btnGenerarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarCodigoActionPerformed
        gencod();
        inhhabilitraAgregar();
        habilitattxtAgregar();
        txtpeliagre.requestFocus();
    }//GEN-LAST:event_btnGenerarCodigoActionPerformed

    private void btnGenerarCodigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarCodigoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerarCodigoMouseClicked

    private void txtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarActionPerformed

    private void tblpeliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpeliMouseClicked
                verDatos();
           
            habilitraActualizar();
            inhabilitattxtActualizar();
    }//GEN-LAST:event_tblpeliMouseClicked

    private void cmbgeneroagreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbgeneroagreKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //emp = cboEmpresa.getSelectedItem();
            Object oo = cmbgeneroagre.getSelectedItem();

            String descripcion2="";
            String codigo2="";

            try{
                codigo2 = (((String[])oo)[0]);
                descripcion2 = (((String[])oo)[1]);
               gencod= codigo2;
                gen=descripcion2;
             }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Error"+e.toString()," ",
                        JOptionPane.INFORMATION_MESSAGE);
             }
            txtactoresagre.setEnabled(true);
           txtactoresagre.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cmbgeneroagreKeyPressed

    private void cmbgeneroagreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbgeneroagreActionPerformed
               // TODO add your handling code here:
    }//GEN-LAST:event_cmbgeneroagreActionPerformed

    private void BtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarActionPerformed
    
                habilitattxtActualizar();
                inhhabilitraActualizar();
                txttitulomodi.requestFocus();
                        
                
    }//GEN-LAST:event_BtnModificarActionPerformed

    private void btnguardarmodiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarmodiActionPerformed
        agr = false;
                mod = true;
                actualizar();
                btnSalir.setEnabled(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnguardarmodiActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void cmbgeneromodiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbgeneromodiKeyPressed
       // TODO add your handling code here:
    }//GEN-LAST:event_cmbgeneromodiKeyPressed

    private void txttitulomodiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttitulomodiActionPerformed
cmbgeneromodi.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txttitulomodiActionPerformed

    private void cmbgeneromodiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbgeneromodiActionPerformed
              // TODO add your handling code here:
    }//GEN-LAST:event_cmbgeneromodiActionPerformed

    private void txtduracionmodiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtduracionmodiActionPerformed
txtpaismodi.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtduracionmodiActionPerformed

    private void txtpaismodiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpaismodiActionPerformed
txtdirectormodi.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtpaismodiActionPerformed

    private void txtdirectormodiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdirectormodiActionPerformed
jtxaPeliculaActores.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtdirectormodiActionPerformed

    private void btnCAncelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCAncelarActionPerformed
        vaciarTextoActualizar();
        BtnBorrar.setEnabled(false);
        btnguardarmodi.setEnabled(false);
        BtnModificar.setEnabled(false);
        btnbuscar.setEnabled(true);
        btnSalir.setEnabled(false);
        btnCAncelar.setEnabled(false);
        
        txtbuscar.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCAncelarActionPerformed

    private void cmbgeneromodiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbgeneromodiMouseClicked
       //emp = cboEmpresa.getSelectedItem();
            
    }//GEN-LAST:event_cmbgeneromodiMouseClicked

    private void BtnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorrarActionPerformed
     fila = tblpeli.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ningun registro");
        } else {

            int msj = JOptionPane.showConfirmDialog(null, "¿Realmente desea borrar el registro?", "Borrar", JOptionPane.YES_NO_OPTION);
            if (msj == JOptionPane.YES_OPTION) {
                borrar();
                limpiarGrilla();
                cargarGrilla();
                
            }
        }     // TODO add your handling code here:
    }//GEN-LAST:event_BtnBorrarActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbuscarActionPerformed
public static String getGenero() {
         return gen;
    }
    //En este metodo capturamos el codigo de la Empresa
    public static String getGeneroCOd() {
         return gencod;
    }
    public static String getGeneroMod() {
         return genmod;
    }
    //En este metodo capturamos el codigo de la Empresa
    public static String getGeneroCOdMod() {
         return gencodmo;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Peliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Peliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Peliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Peliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                Peliculas dialog = new Peliculas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBorrar;
    private javax.swing.JButton BtnModificar;
    private javax.swing.JButton btnCAncelar;
    private javax.swing.JButton btnGenerarCodigo;
    private javax.swing.JButton btnPeliAgregar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSalirAgregar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btncancelarAgregar;
    private javax.swing.JButton btnguardarmodi;
    private javax.swing.JComboBox cmbgeneroagre;
    private javax.swing.JComboBox cmbgeneromodi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel jlblImagenCatalogoPeliculas;
    private javax.swing.JTextField jlblPeliculaTituloGrande;
    private javax.swing.JTextArea jtxaPeliculaActores;
    private javax.swing.JTextArea jtxaPeliculaSinopsis;
    private javax.swing.JTable tblpeli;
    private javax.swing.JTextArea txasinopsisagre;
    private javax.swing.JTextArea txtactoresagre;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtcodigoAgre;
    private javax.swing.JTextField txtcodigomodi;
    private javax.swing.JTextField txtdirectormodi;
    private javax.swing.JTextField txtduracionare;
    private javax.swing.JTextField txtduracionmodi;
    private javax.swing.JTextField txtpaisagre;
    private javax.swing.JTextField txtpaismodi;
    private javax.swing.JTextField txtpeliagre;
    private javax.swing.JTextField txtteleAgre;
    private javax.swing.JTextField txttitulomodi;
    // End of variables declaration//GEN-END:variables
 private void habilitraAgregar(){
        btnGenerarCodigo.setEnabled(true);
        btnPeliAgregar.setEnabled(false);
        btnSalirAgregar.setEnabled(true);
        btncancelarAgregar.setEnabled(false);
            
    }
    private void inhhabilitraAgregar(){
        btnGenerarCodigo.setEnabled(false);
        btnPeliAgregar.setEnabled(true);
        btnSalirAgregar.setEnabled(true);
         btncancelarAgregar.setEnabled(true);
            
    }
    private void habilitattxtAgregar(){
        txtcodigoAgre.setEnabled(false);
        txtpeliagre.setEditable(true);
        txtpaisagre.setEditable(true);
        txtduracionare.setEditable(true);
       
        txtactoresagre.setEditable(true);
       
        cmbgeneroagre.setSelectedItem(true);
        txasinopsisagre.setEditable(true);
    }
    private void inhabilitattxtAgregar(){
        txtcodigoAgre.setEnabled(false);
        txtpeliagre.setEditable(false);
        txtpaisagre.setEditable(false);
        txtduracionare.setEditable(false);
       
        txtactoresagre.setEditable(false);
        
        cmbgeneroagre.setSelectedItem(false);
        txasinopsisagre.setEditable(false);
    }
    private void vaciarTextoAgregar(){
      txtcodigoAgre.setText("");
      txtpeliagre.setText("");
      txtpaisagre.setText("");
      txtdirectormodi.setText("");
      txtduracionare.setText("");
      txtpaisagre.setText("");
      txasinopsisagre.setText("");
      txtactoresagre.setText("");
      
    }
     private void habilitraActualizar(){
        BtnBorrar.setEnabled(true);
        BtnModificar.setEnabled(true);
        btnguardarmodi.setEnabled(false);
        btnSalir.setEnabled(true);
         btnCAncelar.setEnabled(false);
            
    }
    private void inhhabilitraActualizar(){
        BtnBorrar.setEnabled(false);
        btnguardarmodi.setEnabled(true);
        BtnModificar.setEnabled(false);
        btnbuscar.setEnabled(false);
        btnSalir.setEnabled(false);
        btnCAncelar.setEnabled(true);
            
    }
    private void habilitattxtActualizar(){
        cmbgeneromodi.setSelectedItem(false);
        txtcodigomodi.setEditable(true);
        txtduracionmodi.setEditable(true);
        txtpaismodi.setEditable(true);
        txttitulomodi.setEditable(true);
        txtdirectormodi.setEditable(true);
        jtxaPeliculaActores.setEditable(true);
        jtxaPeliculaSinopsis.setEditable(true);
    }
    private void inhabilitattxtActualizar(){
        cmbgeneromodi.setSelectedItem(false);
        txtcodigomodi.setEditable(false);
        txtduracionmodi.setEditable(false);
        txtpaismodi.setEditable(false);
        txttitulomodi.setEditable(false);
        txtdirectormodi.setEditable(false);
        jtxaPeliculaActores.setEditable(false);
        jtxaPeliculaSinopsis.setEditable(false);
    }
    private void vaciarTextoActualizar(){
       
        txtcodigomodi.setText("");
        txtduracionmodi.setText("");
        txtpaismodi.setText("");
        txttitulomodi.setText("");
        txtdirectormodi.setText("");
        jtxaPeliculaActores.setText("");
        jtxaPeliculaSinopsis.setText("");
        cmbgeneromodi.setEnabled(false);
      // jlblImagenCatalogoPeliculas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/incognito.jpg")));
    }
    

   
    
   private void gencod() {
        try{
             ConeccionBD1 z = new ConeccionBD1();
             Connection cn = z.conectar();
           
            Statement stmt = cn.createStatement();
            rs = stmt.executeQuery("SELECT IFNULL(MAX(idPelicula),0)+1 AS codigo FROM pelicula");
            rs.next();
            txtcodigoAgre.setText(rs.getString("codigo"));
        }catch (SQLException exceptionSql){
            JOptionPane.showMessageDialog(null, exceptionSql.getMessage(), "Error de Conexion con la Base de Datos", JOptionPane.ERROR_MESSAGE);
		System.exit(0);
        }
    } 
    private void agregar(){
       codGenero= getGeneroCOd();
         try {
             ConeccionBD1 z = new ConeccionBD1();
             Connection cn = z.conectar();
             Statement stmt = cn.createStatement();
            String sql = "";
                if (agr == true){
                    sql = "INSERT INTO pelicula (idpelicula, PaisPelicula, tituloPelicula, duracionPelicula, directorPelicula, "
                            + "actoresPelicula, sinopsisPelicula,idGenero ) VALUES ('"+ txtcodigoAgre.getText()+"','"+
                           txtpaisagre.getText()+"','"+ txtpeliagre.getText()+"','"+ txtduracionare.getText()+"', "
                            + "'"+ txtdirectormodi.getText()+"','"+ txtactoresagre.getText()+"','"+ txasinopsisagre.getText()+"', "
                            + "'"+codGenero+"')";
                    
                }
                stmt.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "¡Los datos se han insertado de manera satisfactoria!");
                stmt.close();
               
        } catch (SQLException ex) {
            Logger.getLogger(Peliculas.class.getName()).log(Level.SEVERE, null, ex);
        }
         cargarGrilla();
    }
    
    private void actualizar(){
     codGeneroModi= getGeneroCOdMod();
     int color = buscaCodGenero(cmbgeneromodi.getSelectedItem().toString(), "genero");
        try {
        ConeccionBD1 z = new ConeccionBD1();
             Connection cn = z.conectar();
             Statement stmt = cn.createStatement();
             
       String update = "UPDATE pelicula " + "SET "
                        + "PaisPelicula='" + txtpaismodi.getText() + "', "
                        + "tituloPelicula='" + txttitulomodi.getText() + "', "
                        + "duracionPelicula='" + txtduracionmodi.getText() + "', "
                        + "directorPelicula='" + txtdirectormodi.getText() + "', "
                        + "actoresPelicula='" + jtxaPeliculaActores.getText() + "', "
                        + "sinopsisPelicula='" + jtxaPeliculaSinopsis.getText() + "' , "
                        + "idGenero='" + color+ "' "
                        + "WHERE idPelicula='" + txtcodigomodi.getText() + "';";
           
                stmt.executeUpdate(update);
                 JOptionPane.showMessageDialog(null, "Se ha Modificado con exito", "Felicitaciones",JOptionPane.INFORMATION_MESSAGE);
                stmt.close();
                cn.close();
              } catch (SQLException ex) {
                Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
            }  
        cargarGrilla();
                        
                       
    }
   
   

   
    private boolean existeCedulaCliente() {
        boolean existe = false;
        if (bd.existeCedulaCliente(this.txtpeliagre.getText())) {
            existe = true;
        }
        return existe;
    }
   
    private void confGrilla(){
        modelo.addColumn("Codigo"); 
        modelo.addColumn("Pelicula");
        modelo.addColumn("Genero"); 
        modelo.addColumn("Pais");
        modelo.addColumn("Duraccion"); 
        modelo.addColumn("Director");
    
    }
    private void cargarGrilla(){
        modelo.setRowCount(0);
        try {
            String sql = "select Codigo, Pelicula, Genero, Pais, Duraccion, Director "
                    + "  from vistapelicula ";
            if(txtbuscar.getText().trim().length() > 0)
                 sql = sql+" where concat (Pelicula,' ', Genero, ' ', Pais,' ',Director) like '%"+txtbuscar.getText()+"%'";

            sql = sql+" order by Codigo";
            String[] datos = new String[6];
            ConeccionBD1 z = new ConeccionBD1();
             Connection cn = z.conectar();
             Statement stmt = cn.createStatement();
             rs = stmt.executeQuery(sql);
            while(rs.next()){
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4] = rs.getString(5);
               datos[5] = rs.getString(6); 
                
                modelo.addRow(datos);

            }
        } catch (SQLException ex) {
            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
     
     private void borrar(){
        try {
            ConeccionBD1 z = new ConeccionBD1();
             Connection cn = z.conectar(); 
             fila = this.tblpeli.getSelectedRow();
            Object cod_cli=this.tblpeli.getValueAt(fila,0);
            String sql = "DELETE FROM pelicula WHERE idPelicula = "+cod_cli;
            Statement stmt = cn.createStatement();
            stmt.executeUpdate(sql);
        } catch (SQLException ex) {
            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
      private void limpiarGrilla() {   
         while (modelo.getRowCount() > 0)
             modelo.removeRow(0);
     }
      private int buscaCodGenero(String des, String tabla){
       ConeccionBD1 z = new ConeccionBD1();
             Connection cn = z.conectar(); 
          int retorno = 0;
        try {
            
            String sql = "SELECT  idGenero FROM " + tabla + " where descripcionGenero = '" + des + "'";
               Statement stmt = cn.createStatement();
               stmt.executeUpdate(sql);
                rs.next();
                retorno = rs.getInt("idGenero");
        } catch (SQLException ex) {
            Logger.getLogger(Peliculas.class.getName()).log(Level.SEVERE, null, ex);
        }
    return retorno;
    }
      private void verDatos(){
          
        fila = tblpeli.getSelectedRow();

            int cod_col = Integer.parseInt(tblpeli.getValueAt(fila, 0).toString());
        ConeccionBD1 z = new ConeccionBD1();
            Connection cn = z.conectar();
            String sql = "SELECT * from vistapelicula  "
                    + " WHERE Codigo= " + cod_col;
            try {
                Statement st = cn.createStatement();
                rs = st.executeQuery(sql);
                while (rs.next()) {
                //    if (new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/" + cod_col + ".jpg"))==null){
                 //       jlblImagenCatalogoPeliculas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/" + cod_col + ".jpg")));
                   // }
                 //   else{
                       
                     //  jlblImagenCatalogoPeliculas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/incognito.jpg")));
                   // }
                    
                    // cod = rs.getString("");
                    jlblPeliculaTituloGrande.setText(rs.getString("Pelicula"));
                    txtcodigomodi.setText(rs.getString("Codigo"));
                    txttitulomodi.setText(rs.getString("Pelicula"));
                    txtpaismodi.setText(rs.getString("Pais"));
                    cmbgeneromodi.setSelectedItem(rs.getString("Genero"));
                    txtdirectormodi.setText(rs.getString("Director"));
                    txtduracionmodi.setText(rs.getString("Duraccion"));
                    jtxaPeliculaActores.setText(rs.getString("Actores"));
                    jtxaPeliculaSinopsis.setText(rs.getString("Sinopsis"));
                }




            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            } 
      }
      private void cargaGenero(){
          ConeccionBD1 z = new ConeccionBD1();
            Connection cn = z.conectar();
        try {
            String sql = "SELECT * FROM genero order by idGenero ";
                Statement st = cn.createStatement();
                rs = st.executeQuery(sql);
                cmbgeneromodi.removeAllItems();
                while (rs.next()) {
                    cmbgeneromodi.addItem(rs.getString("descripcionGenero"));
    }
    
        } catch (SQLException ex) {
            Logger.getLogger(Peliculas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        
         }
     
    




