/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Programas;

import Clases.*;
import Modelo.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Ruben
 */
public class RegistrarVenta extends javax.swing.JDialog {

    private ConeccionBD1 bd;
    private Cliente cliente;
    private Pelicula pelicula;
    private ResultSet rs;
    private Ejemplar ejemplar;
    private DetalleVenta detalleVenta;
    private Venta venta;
    private ArrayList<Ejemplar> listaEjemplaresPorPelicula;
    private ArrayList<Ejemplar> listaEjemplaresElegidosParaVender;
    private ArrayList<Ejemplar> listaEjemplaresVendidos;
    String nivel, codnivel, funcionario, codfuncionario;
    String tfparam;
    int total;

    /**
     * Creates new form RegistrarVenta
     */
    public RegistrarVenta(java.awt.Frame parent, boolean modal) {

        initComponents();
        traerDatosdeAcceso();
        bd = new ConeccionBD1();
        listaEjemplaresElegidosParaVender = new ArrayList<Ejemplar>();
        listaEjemplaresPorPelicula = new ArrayList<Ejemplar>();
        listaEjemplaresVendidos = new ArrayList<Ejemplar>();

        this.jlblVentaFecha.setText(Base.getFecha());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel17 = new javax.swing.JPanel();
        txtnivel = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        txtfactura = new javax.swing.JTextField();
        jLabel78 = new javax.swing.JLabel();
        txtfuncionario = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtcodfun = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jtxfPeliculaTitulo = new javax.swing.JTextField();
        jbtnVerCatalogoPeliculas = new javax.swing.JButton();
        jtxfPeliculaGenero = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblPeliculaEjemplares = new javax.swing.JTable();
        jlblPeliculaImagen = new javax.swing.JLabel();
        jbtnLimpiarPanelPelicula = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtxaPeliculaSinopsis = new javax.swing.JTextArea();
        jbtnAgregarEjemplaresAlaTablaDetalleAlquiler = new javax.swing.JButton();
        jbtnVerEjemplaresPorPelicula = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jtxfEjemplarCantidad = new javax.swing.JTextField();
        jcmbxEjemplarFormato = new javax.swing.JComboBox();
        jtxfPeliculaStockDVD = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jtxfPeliculaStockBluRay = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jtxfPeliculaStock = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblDetalleVenta = new javax.swing.JTable();
        jbtnRegistrarVenta = new javax.swing.JButton();
        jbtnSalir = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jtxfVentaMontoTotal = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jlblVentaHora = new javax.swing.JLabel();
        jbtnQuitarPelicula = new javax.swing.JButton();
        jlblVentaFecha = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jlblVentaFecha1 = new javax.swing.JLabel();
        jlblVentaCliente = new javax.swing.JLabel();
        jlblVentaDireccion = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jtxfClienteCI = new javax.swing.JTextField();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jtxfClienteNombres = new javax.swing.JTextField();
        jbtnBuscarCliente = new javax.swing.JButton();
        jLabel75 = new javax.swing.JLabel();
        jtxfClienteApellidos = new javax.swing.JTextField();
        jLabel76 = new javax.swing.JLabel();
        jtxfClienteTipo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("REGISTRAR VENTA");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 102, 102));
        jSeparator1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(255, 255, 0)));
        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 46, 1255, 10));

        jPanel17.setBackground(new java.awt.Color(0, 0, 0));
        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)), "Detalle Factura", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 255, 0))); // NOI18N
        jPanel17.setForeground(new java.awt.Color(0, 102, 102));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtnivel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtnivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnivelActionPerformed(evt);
            }
        });
        jPanel17.add(txtnivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 170, -1));

        jLabel68.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 255, 255));
        jLabel68.setText("Nivel:");
        jPanel17.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 100, -1));

        jLabel77.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(255, 255, 255));
        jLabel77.setText("Nro Factura:");
        jPanel17.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, -1));

        txtfactura.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtfactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfacturaActionPerformed(evt);
            }
        });
        jPanel17.add(txtfactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 40, -1));

        jLabel78.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(255, 255, 255));
        jLabel78.setText("Funcionario:");
        jPanel17.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 100, -1));

        txtfuncionario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtfuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfuncionarioActionPerformed(evt);
            }
        });
        jPanel17.add(txtfuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 170, -1));

        jButton1.setText("Generar Factura");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel17.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 120, -1));
        jPanel17.add(txtcodfun, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 40, -1));

        jPanel1.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 560, 130));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)), "Elegir Película", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 255, 0))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Genero:");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jtxfPeliculaTitulo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtxfPeliculaTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxfPeliculaTituloActionPerformed(evt);
            }
        });
        jPanel4.add(jtxfPeliculaTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 410, -1));

        jbtnVerCatalogoPeliculas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnVerCatalogoPeliculas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/catalogoPeliculas.png"))); // NOI18N
        jbtnVerCatalogoPeliculas.setActionCommand("Ver Ejemplares");
        jbtnVerCatalogoPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVerCatalogoPeliculasActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnVerCatalogoPeliculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 200, 40));

        jtxfPeliculaGenero.setEditable(false);
        jtxfPeliculaGenero.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel4.add(jtxfPeliculaGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 120, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Título:");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 51)), "Ejemplares", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 255, 0))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtblPeliculaEjemplares.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nro", "Código", "Formato", "Precio", "Estado"
            }
        ));
        jtblPeliculaEjemplares.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblPeliculaEjemplaresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblPeliculaEjemplares);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 19, 550, 100));

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 580, 120));

        jlblPeliculaImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jlblPeliculaImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, -1, 230));

        jbtnLimpiarPanelPelicula.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnLimpiarPanelPelicula.setText("Limpiar");
        jbtnLimpiarPanelPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLimpiarPanelPeliculaActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnLimpiarPanelPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, -1, -1));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)), "Sinopsis", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 255, 51))); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane3.setEnabled(false);

        jtxaPeliculaSinopsis.setBackground(new java.awt.Color(0, 0, 0));
        jtxaPeliculaSinopsis.setColumns(20);
        jtxaPeliculaSinopsis.setEditable(false);
        jtxaPeliculaSinopsis.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jtxaPeliculaSinopsis.setForeground(new java.awt.Color(255, 255, 255));
        jtxaPeliculaSinopsis.setRows(5);
        jtxaPeliculaSinopsis.setEnabled(false);
        jScrollPane3.setViewportView(jtxaPeliculaSinopsis);

        jPanel6.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 19, 380, 100));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 410, 130));

        jbtnAgregarEjemplaresAlaTablaDetalleAlquiler.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnAgregarEjemplaresAlaTablaDetalleAlquiler.setText("Agregar A la Venta");
        jbtnAgregarEjemplaresAlaTablaDetalleAlquiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAgregarEjemplaresAlaTablaDetalleAlquilerActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnAgregarEjemplaresAlaTablaDetalleAlquiler, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        jbtnVerEjemplaresPorPelicula.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnVerEjemplaresPorPelicula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/verEjemplares.jpg"))); // NOI18N
        jbtnVerEjemplaresPorPelicula.setText("Ejemplares");
        jbtnVerEjemplaresPorPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVerEjemplaresPorPeliculaActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnVerEjemplaresPorPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 120, 30));

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)), "Elegir Formato y Cantidad de Ejemplares", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 255, 0))); // NOI18N

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Formato:");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Cantidad:");

        jtxfEjemplarCantidad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jcmbxEjemplarFormato.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DVD", "Blu-Ray" }));
        jcmbxEjemplarFormato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbxEjemplarFormatoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcmbxEjemplarFormato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxfEjemplarCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel22)
                    .addComponent(jtxfEjemplarCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcmbxEjemplarFormato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 410, 50));

        jtxfPeliculaStockDVD.setEditable(false);
        jtxfPeliculaStockDVD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel4.add(jtxfPeliculaStockDVD, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 40, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Stock DVD:");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Stock Blu-Ray:");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, -1));

        jtxfPeliculaStockBluRay.setEditable(false);
        jtxfPeliculaStockBluRay.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel4.add(jtxfPeliculaStockBluRay, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 40, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Stock:");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jtxfPeliculaStock.setEditable(false);
        jtxfPeliculaStock.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel4.add(jtxfPeliculaStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 40, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 610, 500));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)), "Venta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 255, 0))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)), "Detalle de la Venta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 255, 0))); // NOI18N

        jtblDetalleVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Cantidad", "Codigo Ejemplar", "Tiitulo Ejemplar", "Formato Ejemplar", "Precio Ejemplar", "Monto Linea"
            }
        ));
        jtblDetalleVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblDetalleVentaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtblDetalleVenta);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
        );

        jbtnRegistrarVenta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnRegistrarVenta.setText("Registrar Venta");
        jbtnRegistrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegistrarVentaActionPerformed(evt);
            }
        });

        jbtnSalir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnSalir.setText("Salir");
        jbtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalirActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Monto Total GS :");

        jtxfVentaMontoTotal.setEditable(false);
        jtxfVentaMontoTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Fecha y Hora:");

        jlblVentaHora.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblVentaHora.setForeground(new java.awt.Color(255, 255, 0));

        jbtnQuitarPelicula.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnQuitarPelicula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/icon_30.png"))); // NOI18N
        jbtnQuitarPelicula.setText("Quitar Pelicula");
        jbtnQuitarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnQuitarPeliculaActionPerformed(evt);
            }
        });

        jlblVentaFecha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblVentaFecha.setForeground(new java.awt.Color(255, 255, 0));
        jlblVentaFecha.setText("Fecha");

        jLabel71.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(255, 255, 255));
        jLabel71.setText("Cliente:");

        jLabel72.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(255, 255, 255));
        jLabel72.setText("Dirección:");

        jlblVentaFecha1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblVentaFecha1.setForeground(new java.awt.Color(255, 255, 0));

        jlblVentaCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblVentaCliente.setForeground(new java.awt.Color(255, 255, 0));

        jlblVentaDireccion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblVentaDireccion.setForeground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jbtnQuitarPelicula)
                        .addGap(139, 139, 139)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxfVentaMontoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jbtnRegistrarVenta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnSalir))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel24)
                                        .addComponent(jLabel71)
                                        .addComponent(jLabel72))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addComponent(jlblVentaFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jlblVentaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jlblVentaDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jlblVentaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(17, Short.MAX_VALUE))))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(123, 123, 123)
                    .addComponent(jlblVentaFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(343, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlblVentaFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(jlblVentaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel71)
                    .addComponent(jlblVentaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel72)
                    .addComponent(jlblVentaDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxfVentaMontoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnQuitarPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnRegistrarVenta)
                    .addComponent(jbtnSalir))
                .addGap(20, 20, 20))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jlblVentaFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(352, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, 560, 400));

        jPanel18.setBackground(new java.awt.Color(0, 0, 0));
        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)), "Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 255, 0))); // NOI18N
        jPanel18.setForeground(new java.awt.Color(0, 102, 102));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxfClienteCI.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtxfClienteCI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxfClienteCIActionPerformed(evt);
            }
        });
        jPanel18.add(jtxfClienteCI, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 20, 102, -1));

        jLabel73.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(255, 255, 255));
        jLabel73.setText("Nombres:");
        jPanel18.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel74.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(255, 255, 255));
        jLabel74.setText("Nro.CI");
        jPanel18.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 22, 50, -1));

        jtxfClienteNombres.setEditable(false);
        jtxfClienteNombres.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel18.add(jtxfClienteNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 153, -1));

        jbtnBuscarCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/buscar_cliente.jpg"))); // NOI18N
        jbtnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscarClienteActionPerformed(evt);
            }
        });
        jPanel18.add(jbtnBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 30, 30));

        jLabel75.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(255, 255, 255));
        jLabel75.setText("Apellidos:");
        jPanel18.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        jtxfClienteApellidos.setEditable(false);
        jtxfClienteApellidos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel18.add(jtxfClienteApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 60, 230, -1));

        jLabel76.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(255, 255, 255));
        jLabel76.setText("Tipo:");
        jPanel18.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 23, -1, -1));

        jtxfClienteTipo.setEditable(false);
        jtxfClienteTipo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jtxfClienteTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxfClienteTipoActionPerformed(evt);
            }
        });
        jPanel18.add(jtxfClienteTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 20, 130, -1));

        jPanel1.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 560, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1203, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnVerCatalogoPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVerCatalogoPeliculasActionPerformed
        //aqui definimos una matriz de tipo jTexfield y el numero de columnas
        JTextField[] tfParam = new JTextField[2];
        // se le asigna donde va a mostrar el valor de cada columna
        tfParam[1] = this.jtxfPeliculaTitulo;

        // instanciamos nuestra clase ventanaBuscar que se encuentra en el paquete clases
        // creamos la consulta con select de acuerdo a lo que queremos mostrar
        // en nuestra VentanaBuscar 
        CatalogoPeli pp = new CatalogoPeli("select Codigo, Pelicula from vistapelicula where Pelicula like ",
                new String[]{"CODIGO", "PELICULA"}, 2, tfParam);
        // Colocamos un titulo en nuestra VentanaBuscar con el comando setTitle
        // en esta linea hacemos que sea visible nuestra ventana Buscar
        // con el comando setVisible
        pp.setVisible(true);
        // habilitamos el txtcantidad
        limpiarPanelPelicula();
        jtxfPeliculaStock.setText("");

        // CatalagoPelicula vcp = new CatalagoPelicula(null, rootPaneCheckingEnabled);
        //vcp.setVisible(true);
        //vcp.setDefaultCloseOperation(2);
    }//GEN-LAST:event_jbtnVerCatalogoPeliculasActionPerformed

    private void jtblPeliculaEjemplaresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblPeliculaEjemplaresMouseClicked
        int i = this.jtblPeliculaEjemplares.getSelectedRow();

        if (this.jtblPeliculaEjemplares.getValueAt(i, 2).equals("DVD")) {
            this.jcmbxEjemplarFormato.setSelectedIndex(0);
        }
        if (this.jtblPeliculaEjemplares.getValueAt(i, 2).equals("Blu-Ray")) {
            this.jcmbxEjemplarFormato.setSelectedIndex(1);
        }
    }//GEN-LAST:event_jtblPeliculaEjemplaresMouseClicked

    private void jbtnLimpiarPanelPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLimpiarPanelPeliculaActionPerformed
        this.limpiarPanelPelicula();
    }//GEN-LAST:event_jbtnLimpiarPanelPeliculaActionPerformed

    private void jbtnAgregarEjemplaresAlaTablaDetalleAlquilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAgregarEjemplaresAlaTablaDetalleAlquilerActionPerformed
        limpiarTablaDetalleVenta();
        leerFormatoyCantidadElegida();
        actualizarLosEstadosEnLaTablaEjemplaresPorPeliculaAEstadoElegido(listaEjemplaresElegidosParaVender);
        ActualizarLaTablaDetalleVentaconLaListaActualDeEjemplaresElegidos();
        this.jlblVentaHora.setText(Base.getHora());
        txtnivel.requestFocus();
        txtnivel.setEditable(true);
    }//GEN-LAST:event_jbtnAgregarEjemplaresAlaTablaDetalleAlquilerActionPerformed

    private void jbtnVerEjemplaresPorPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVerEjemplaresPorPeliculaActionPerformed
        this.listaEjemplaresPorPelicula.clear();
        String tituloPelicula = this.jtxfPeliculaTitulo.getText().trim().toUpperCase();

        if (existeTituloPelicula(tituloPelicula)) {
            pelicula = bd.obtenerPeliculaPorTitulo(tituloPelicula);
            listaEjemplaresPorPelicula = bd.obtenerEjemplaresPorPeliculaConEstadoLibre(pelicula);

            int stockDVD = 0;
            int stockBluRay = 0;

            this.jtxfPeliculaGenero.setText(pelicula.getGenero().getDescripcion());
            this.jtxfPeliculaTitulo.setText(tituloPelicula);
            this.jtxaPeliculaSinopsis.setText(pelicula.getSinopsis());
            this.jlblPeliculaImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/" + this.pelicula.getId() + ".jpg")));

            for (int i = 0; i < this.listaEjemplaresPorPelicula.size(); i++) {

                this.jtblPeliculaEjemplares.setValueAt((i + 1), i, 0);
                this.jtblPeliculaEjemplares.setValueAt(this.listaEjemplaresPorPelicula.get(i).getId(), i, 1);
                this.jtblPeliculaEjemplares.setValueAt(this.listaEjemplaresPorPelicula.get(i).getFormato(), i, 2);
                this.jtblPeliculaEjemplares.setValueAt(this.listaEjemplaresPorPelicula.get(i).getPrecioAlquiler(), i, 3);
                this.jtblPeliculaEjemplares.setValueAt(this.listaEjemplaresPorPelicula.get(i).getEstado(), i, 4);

                if (listaEjemplaresPorPelicula.get(i).getFormato().equalsIgnoreCase("DVD")) {
                    stockDVD++;
                }

                if (listaEjemplaresPorPelicula.get(i).getFormato().equalsIgnoreCase("Blu-Ray")) {
                    stockBluRay++;
                }

            }
            this.jtxfPeliculaStock.setText("" + (stockDVD + stockBluRay));
            this.jtxfPeliculaStockDVD.setText("" + stockDVD);
            this.jtxfPeliculaStockBluRay.setText("" + stockBluRay);
        } else {
            JOptionPane.showMessageDialog(null, "La Pelicula :" + tituloPelicula + " no existe!");
        }
    }//GEN-LAST:event_jbtnVerEjemplaresPorPeliculaActionPerformed

    private void jtblDetalleVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblDetalleVentaMouseClicked

   }//GEN-LAST:event_jtblDetalleVentaMouseClicked

    private void jbtnRegistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegistrarVentaActionPerformed

        if (this.jtxfClienteNombres.getText().length() != 0) {
            String fecha = this.jlblVentaFecha.getText();
            String hora = this.jlblVentaHora.getText();
            Double montoTotal = Base.convertirCadenaReal(this.jtxfVentaMontoTotal.getText());
            int Funcionario = Base.convertirCadenaEntero(this.txtcodfun.getText());
            int codigo = Base.convertirCadenaEntero(this.txtfactura.getText());

            venta = new Venta(codigo, fecha, hora, montoTotal, cliente, Funcionario);
            bd.insertarVenta(venta);

            venta = bd.obtenerVenta();

            insertarDetalleVentaALaBaseDatos();

        } else {
            JOptionPane.showMessageDialog(null, "Cliente no existe, debe ingresar o registrar sus datos!");

        }
    }//GEN-LAST:event_jbtnRegistrarVentaActionPerformed

    private void jbtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtnSalirActionPerformed

    private void jbtnQuitarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnQuitarPeliculaActionPerformed
        reinicializarEstadoDeLaTablaEjemplaresPorPelicula();
        int i = this.jtblDetalleVenta.getSelectedRow();
        this.listaEjemplaresElegidosParaVender.remove(i);
        limpiarTablaDetalleVenta();
        actualizarLosEstadosEnLaTablaEjemplaresPorPeliculaAEstadoElegido(listaEjemplaresElegidosParaVender);
        ActualizarLaTablaDetalleVentaconLaListaActualDeEjemplaresElegidos();
    }//GEN-LAST:event_jbtnQuitarPeliculaActionPerformed

    private void jtxfPeliculaTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxfPeliculaTituloActionPerformed
        jbtnVerEjemplaresPorPelicula.requestFocus();
        jbtnVerEjemplaresPorPelicula.doClick();// TODO add your handling code here:
    }//GEN-LAST:event_jtxfPeliculaTituloActionPerformed

    private void jcmbxEjemplarFormatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbxEjemplarFormatoActionPerformed
        jtxfEjemplarCantidad.requestFocus();
        jtxfEjemplarCantidad.setEditable(true);// TODO add your handling code here:
    }//GEN-LAST:event_jcmbxEjemplarFormatoActionPerformed

    private void txtnivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnivelActionPerformed
        jbtnBuscarCliente.requestFocus();
        jbtnBuscarCliente.doClick();// TODO add your handling code here:
    }//GEN-LAST:event_txtnivelActionPerformed

    private void jtxfClienteCIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxfClienteCIActionPerformed
        jbtnBuscarCliente.requestFocus();
        jbtnBuscarCliente.doClick();// TODO add your handling code here:
    }//GEN-LAST:event_jtxfClienteCIActionPerformed

    private void jbtnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscarClienteActionPerformed
        String CI = this.jtxfClienteCI.getText();

        if (existeCICliente(CI)) {
            cliente = bd.obtenerClientePorCI(CI);

            this.jtxfClienteNombres.setText(cliente.getNombres());
            this.jtxfClienteApellidos.setText(cliente.getApellidos());
            this.jtxfClienteTipo.setText(cliente.getTipo());

            this.jlblVentaCliente.setText(cliente.getNombres() + " " + cliente.getApellidos());
            this.jlblVentaDireccion.setText(cliente.getDireccion());
        } else {
            JOptionPane.showMessageDialog(null, "Cliente no existe, puede registrar sus datos!");
            Clientes vcm = new Clientes(null, rootPaneCheckingEnabled);
            vcm.setVisible(true);
            vcm.setDefaultCloseOperation(2);
        }   // TODO add your handling code here:
    }//GEN-LAST:event_jbtnBuscarClienteActionPerformed

    private void txtfacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfacturaActionPerformed

    private void txtfuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfuncionarioActionPerformed

    private void jtxfClienteTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxfClienteTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxfClienteTipoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        gencod();
        //    traerDatosdeAcceso();


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                RegistrarVenta dialog = new RegistrarVenta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbtnAgregarEjemplaresAlaTablaDetalleAlquiler;
    private javax.swing.JButton jbtnBuscarCliente;
    private javax.swing.JButton jbtnLimpiarPanelPelicula;
    private javax.swing.JButton jbtnQuitarPelicula;
    private javax.swing.JButton jbtnRegistrarVenta;
    private javax.swing.JButton jbtnSalir;
    private javax.swing.JButton jbtnVerCatalogoPeliculas;
    private javax.swing.JButton jbtnVerEjemplaresPorPelicula;
    private javax.swing.JComboBox jcmbxEjemplarFormato;
    private javax.swing.JLabel jlblPeliculaImagen;
    private javax.swing.JLabel jlblVentaCliente;
    private javax.swing.JLabel jlblVentaDireccion;
    private javax.swing.JLabel jlblVentaFecha;
    private javax.swing.JLabel jlblVentaFecha1;
    private javax.swing.JLabel jlblVentaHora;
    private javax.swing.JTable jtblDetalleVenta;
    private javax.swing.JTable jtblPeliculaEjemplares;
    private javax.swing.JTextArea jtxaPeliculaSinopsis;
    private javax.swing.JTextField jtxfClienteApellidos;
    private javax.swing.JTextField jtxfClienteCI;
    private javax.swing.JTextField jtxfClienteNombres;
    private javax.swing.JTextField jtxfClienteTipo;
    private javax.swing.JTextField jtxfEjemplarCantidad;
    private javax.swing.JTextField jtxfPeliculaGenero;
    private javax.swing.JTextField jtxfPeliculaStock;
    private javax.swing.JTextField jtxfPeliculaStockBluRay;
    private javax.swing.JTextField jtxfPeliculaStockDVD;
    private javax.swing.JTextField jtxfPeliculaTitulo;
    private javax.swing.JTextField jtxfVentaMontoTotal;
    private javax.swing.JTextField txtcodfun;
    private javax.swing.JTextField txtfactura;
    private javax.swing.JTextField txtfuncionario;
    private javax.swing.JTextField txtnivel;
    // End of variables declaration//GEN-END:variables
private boolean existeCICliente(String CI) {
        return bd.existeCedulaCliente(CI);
    }

    private void limpiarPanelPelicula() {
        this.jtxfPeliculaTitulo.setText("");
        this.jtxfPeliculaGenero.setText("");
        this.jtxaPeliculaSinopsis.setText("");
        this.jtxfPeliculaStockDVD.setText("");
        this.jtxfPeliculaStockBluRay.setText("");

        jlblPeliculaImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/incognito.jpg")));

        for (int i = 0; i < this.jtblPeliculaEjemplares.getRowCount(); i++) {
            this.jtblPeliculaEjemplares.setValueAt("", i, 0);
            this.jtblPeliculaEjemplares.setValueAt("", i, 1);
            this.jtblPeliculaEjemplares.setValueAt("", i, 2);
            this.jtblPeliculaEjemplares.setValueAt("", i, 3);
            this.jtblPeliculaEjemplares.setValueAt("", i, 4);

        }

        this.jtxfEjemplarCantidad.setText("");
    }

    private boolean existeTituloPelicula(String tituloPelicula) {
        return bd.existeTituloPelicula(tituloPelicula);
    }

    private void limpiarTablaDetalleVenta() {
        for (int i = 0; i < jtblDetalleVenta.getRowCount(); i++) {
            this.jtblDetalleVenta.setValueAt("", i, 0);
            this.jtblDetalleVenta.setValueAt("", i, 1);
            this.jtblDetalleVenta.setValueAt("", i, 2);
            this.jtblDetalleVenta.setValueAt("", i, 3);
            this.jtblDetalleVenta.setValueAt("", i, 4);
            this.jtblDetalleVenta.setValueAt("", i, 5);

        }
    }

    private void leerFormatoyCantidadElegida() {
        int cantidadElegida = Base.convertirCadenaEntero(this.jtxfEjemplarCantidad.getText().trim());
        String formatoElegido = (String) this.jcmbxEjemplarFormato.getSelectedItem();

        //DVD
        if (formatoElegido.equalsIgnoreCase("DVD")) {
            int j = 0;
            for (int k = 0; k < this.listaEjemplaresPorPelicula.size(); k++) {
                Ejemplar ej = this.listaEjemplaresPorPelicula.get(k);
                if (j < cantidadElegida) {
                    if (ej.getFormato().equalsIgnoreCase("DVD") && ej.getEstado().equalsIgnoreCase("libre")) {
                        ej.setEstado("Elegido");
                        listaEjemplaresElegidosParaVender.add(j, ej);
                        j++;
                    }
                }
            }
            if (j == 0) {
                JOptionPane.showMessageDialog(null, "No hay ejemplares Disponibles en formato DVD");
            }
        }
        //BLU-RAY
        if (this.jcmbxEjemplarFormato.getSelectedIndex() == 1) {
            int j = 0;
            for (int k = 0; k < this.listaEjemplaresPorPelicula.size(); k++) {
                Ejemplar ej = this.listaEjemplaresPorPelicula.get(k);
                if (j < cantidadElegida) {
                    if (ej.getFormato().equalsIgnoreCase("Blu-Ray") && ej.getEstado().equalsIgnoreCase("Libre")) {
                        ej.setEstado("Elegido");
                        listaEjemplaresElegidosParaVender.add(j, ej);
                        j++;
                    }
                }

            }
            if (j == 0) {
                JOptionPane.showMessageDialog(null, "No hay ejemplares Disponibles en formato Blu-Ray");
            }
        }
    }

    private void actualizarLosEstadosEnLaTablaEjemplaresPorPeliculaAEstadoElegido(ArrayList<Ejemplar> listaEjemplaresElegidosParaVender) {
        for (int i = 0; i < this.listaEjemplaresPorPelicula.size(); i++) {
            for (int k = 0; k < listaEjemplaresElegidosParaVender.size(); k++) {
                if (this.jtblPeliculaEjemplares.getValueAt(i, 1).equals(listaEjemplaresElegidosParaVender.get(k).getId())) {
                    this.jtblPeliculaEjemplares.setValueAt("Elegido", i, 4);
                }
            }
        }
    }

    private void ActualizarLaTablaDetalleVentaconLaListaActualDeEjemplaresElegidos() {
        Double montoTotalVenta = 0.00;
        for (int i = 0; i < this.listaEjemplaresElegidosParaVender.size(); i++) {
            this.jtblDetalleVenta.setValueAt(1, i, 0);
            this.jtblDetalleVenta.setValueAt(this.listaEjemplaresElegidosParaVender.get(i).getId(), i, 1);
            this.jtblDetalleVenta.setValueAt(this.listaEjemplaresElegidosParaVender.get(i).getPelicula().getTitulo(), i, 2);
            this.jtblDetalleVenta.setValueAt(this.listaEjemplaresElegidosParaVender.get(i).getFormato(), i, 3);
            this.jtblDetalleVenta.setValueAt(this.listaEjemplaresElegidosParaVender.get(i).getPrecioVenta(), i, 4);
            this.jtblDetalleVenta.setValueAt(this.listaEjemplaresElegidosParaVender.get(i).getPrecioVenta(), i, 5);
            montoTotalVenta += this.listaEjemplaresElegidosParaVender.get(i).getPrecioVenta();

        }

        this.jtxfVentaMontoTotal.setText("" + montoTotalVenta);
    }

    private void reinicializarEstadoDeLaTablaEjemplaresPorPelicula() {
        for (int i = 0; i < this.listaEjemplaresPorPelicula.size(); i++) {
            this.jtblPeliculaEjemplares.setValueAt("libre", i, 4);
        }
    }

    private void insertarDetalleVentaALaBaseDatos() {
        for (int i = 0; i < this.listaEjemplaresElegidosParaVender.size(); i++) {
            Integer cantidadLinea = (Integer) this.jtblDetalleVenta.getValueAt(i, 0);
            String codigoEjemplar = (String) this.jtblDetalleVenta.getValueAt(i, 1);

            System.out.println("codigoejemplar:" + codigoEjemplar);
            ejemplar = bd.obtenerEjemplarPorId(codigoEjemplar);
            System.out.println("ejemplar:" + ejemplar.getId());

            listaEjemplaresVendidos.add(i, ejemplar);

            Double montoLinea = (Double) this.jtblDetalleVenta.getValueAt(i, 5);
            detalleVenta = new DetalleVenta(cantidadLinea, montoLinea, venta, ejemplar);
            bd.insertarDetalleVenta(detalleVenta);
            actualizarLosEstadosEnLaTablaEjemplaresPorPeliculaAEstadoVendido(listaEjemplaresVendidos);
        }

        String cantidadAgregar = this.jtxfEjemplarCantidad.getText();
        String Stock = this.jtxfPeliculaStock.getText();

        try {
            int cantidadAgregarEntero = Integer.parseInt(cantidadAgregar);
            int stockEntero = Integer.parseInt(Stock);
            total = stockEntero - cantidadAgregarEntero;

            System.out.println(total);
        } catch (NumberFormatException ex) {

            ex.printStackTrace();
            System.out.println("Aca se dio la excepcion del numero entero");
        }

        String idpelicula = this.pelicula.getId();

        bd.actualizarRegistro("pelicula", "Stock_Pelicula=" + total + "",
                "idPelicula=" + idpelicula);
        JOptionPane.showMessageDialog(this, "Los datos de la venta han sido confirmados con éxito");
        limpiarTodoElPanelRegistrarVenta();
    }

    private void actualizarLosEstadosEnLaTablaEjemplaresPorPeliculaAEstadoVendido(ArrayList<Ejemplar> listaEjemplaresVendidos) {
        for (int i = 0; i < this.listaEjemplaresPorPelicula.size(); i++) {
            for (int k = 0; k < listaEjemplaresVendidos.size(); k++) {

                if (this.jtblPeliculaEjemplares.getValueAt(i, 1).equals(listaEjemplaresVendidos.get(k).getId())) {
                    this.jtblPeliculaEjemplares.setValueAt("Vendido", i, 4);
                    bd.actualizarEstadoEjemplarComoVendido(this.listaEjemplaresPorPelicula.get(i));
                }
            }
        }
    }

    private void limpiarTodoElPanelRegistrarVenta() {
        limpiarPanelPelicula();
        limpiarPanelCliente();
        limpiarPanelVenta();
        limpiarPanelDetalles();
        this.listaEjemplaresPorPelicula.clear();
        this.listaEjemplaresElegidosParaVender.clear();
        this.listaEjemplaresVendidos.clear();
    }

    private void limpiarPanelDetalles() {
        this.txtnivel.setText("");
        this.txtfactura.setText("");
        this.txtcodfun.setText("");
        this.txtfuncionario.setText("");
    }

    private void limpiarPanelCliente() {

        this.jtxfClienteNombres.setText("");
        this.jtxfClienteApellidos.setText("");
        this.jtxfClienteTipo.setText("");
        this.jtxfClienteCI.setText("");
    }

    private void limpiarPanelVenta() {
        this.jlblVentaHora.setText("");
        this.jtxfVentaMontoTotal.setText("");
        this.jlblVentaCliente.setText("");
        this.jlblVentaDireccion.setText("");

        for (int i = 0; i < this.jtblDetalleVenta.getRowCount(); i++) {
            this.jtblDetalleVenta.setValueAt("", i, 0);
            this.jtblDetalleVenta.setValueAt("", i, 1);
            this.jtblDetalleVenta.setValueAt("", i, 2);
            this.jtblDetalleVenta.setValueAt("", i, 3);
            this.jtblDetalleVenta.setValueAt("", i, 4);
            this.jtblDetalleVenta.setValueAt("", i, 5);

        }
    }

    private void gencod() {
        try {
            ConeccionBD1 z = new ConeccionBD1();
            Connection cn = z.conectar();

            Statement stmt = cn.createStatement();
            rs = stmt.executeQuery("SELECT IFNULL(MAX(idVenta),0)+1 AS codigo FROM venta");
            rs.next();
            txtfactura.setText(rs.getString("codigo"));
        } catch (SQLException exceptionSql) {
            JOptionPane.showMessageDialog(null, exceptionSql.getMessage(), "Error de Conexion con la Base de Datos", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
    }

    private void traerDatosdeAcceso() {
////////////////trae la descripcion y codigo de la sucursal desde el acceso///////////
        //funcionario = Programas.Acceso.getFuncionario();

        txtfuncionario.setText(ConeccionBD1.UsuaSt);
        txtfuncionario.repaint();

        // codfuncionario = Programas.Acceso.getFuncionariocod();
        txtcodfun.setText(ConeccionBD1.CodUsuSt);
        txtcodfun.repaint();

        // nivel = Programas.Acceso.getNivel();
        txtnivel.setText(ConeccionBD1.cargoSt);
        txtnivel.repaint();
        txtfactura.setEnabled(false);
        txtcodfun.setEnabled(false);
        txtfuncionario.setEnabled(false);
        txtnivel.setEnabled(false);
    }

}
