/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Clases;
import Clases.ConeccionBD1;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import Modelo.Cliente;
import Modelo.Genero;
import Modelo.Pelicula;
import java.util.ArrayList;
import javax.swing.JTextField;
import clases.ModeloTabla;
import java.awt.BorderLayout;
import java.sql.ResultSet;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Ruben
 */
public class CatalogoPelicula extends javax.swing.JFrame {
private ConeccionBD1 bd;
   private ArrayList<Pelicula> listaPeliculas;
   private ResultSet rs;
   private boolean error;
   private Cliente cliente;
   boolean agr, mod, bor = false;
   private Pelicula pelicula;
    private Genero genero;
    private boolean activoBuscarPorGenero;
    private boolean activoBuscarPorTitulo;
    private boolean activoVerTodosLosGeneros;    
    private int i;
    int col;
    String[] nom;
    ArrayList<String[]> val = new ArrayList<String[]>();
    String query;
    String des;
    int cod;
    Object[] tfParam;
    int fila = 0;
    /**
     * Creates new form CatalogoPelicula
     */
    public CatalogoPelicula(String consulta_sql,String[] nombre_columnas,int cantidad_columnas,Object[] objetos_pa_devolver_resultado) {
       this.query  =consulta_sql;
        this.nom = nombre_columnas;
        this.col = cantidad_columnas;
        this.tfParam = objetos_pa_devolver_resultado;
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.jtxfBuscarPorTitulo.enable(false);
        this.activoBuscarPorGenero = false;
        this.activoBuscarPorTitulo = true;
        this.activoVerTodosLosGeneros = true;
        bd= new ConeccionBD1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel7 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jtxfBuscarPorTitulo = new javax.swing.JTextField();
        jbtnVerPeliculas = new javax.swing.JButton();
        lo = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtblDetalle = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jlblPeliculaTituloGrande = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jlblPeliculaTitulo = new javax.swing.JLabel();
        jlblPeliculaGenero = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jlblPeliculaDuracion = new javax.swing.JLabel();
        jlblPeliculaPais = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jlblPeliculaDirector = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxaPeliculaActores = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxaPeliculaSinopsis = new javax.swing.JTextArea();
        jlblImagenCatalogoPeliculas = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbtnPeliculaAnterior = new javax.swing.JButton();
        jbtnPeliculaSiguiente = new javax.swing.JButton();
        jlblPeliculaGeneroSeleccionado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 0));
        jLabel20.setText("CATÁLOGO DE PELÍCULAS");

        jSeparator1.setForeground(new java.awt.Color(0, 102, 102));
        jSeparator1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(255, 255, 0)));
        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Buscar Por", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(255, 204, 0)));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Título:");

        jtxfBuscarPorTitulo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jbtnVerPeliculas.setBackground(new java.awt.Color(255, 255, 255));
        jbtnVerPeliculas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnVerPeliculas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/verPelicula.png"))); // NOI18N
        jbtnVerPeliculas.setText("Ver");
        jbtnVerPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVerPeliculasActionPerformed(evt);
            }
        });

        lo.setBackground(new java.awt.Color(0, 0, 0));
        lo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)), "Detalles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(255, 102, 0)));

        jtblDetalle.setModel(new ModeloTabla(col, nom, val));
        jtblDetalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblDetalleMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jtblDetalle);

        javax.swing.GroupLayout loLayout = new javax.swing.GroupLayout(lo);
        lo.setLayout(loLayout);
        loLayout.setHorizontalGroup(
            loLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        loLayout.setVerticalGroup(
            loLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(30, 30, 30)
                        .addComponent(jtxfBuscarPorTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jbtnVerPeliculas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jtxfBuscarPorTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnVerPeliculas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), "Peliculas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(255, 153, 0)));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)), "Detalle", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(255, 102, 0)));

        jlblPeliculaTituloGrande.setBackground(new java.awt.Color(0, 0, 0));
        jlblPeliculaTituloGrande.setEditable(false);
        jlblPeliculaTituloGrande.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblPeliculaTituloGrande.setForeground(new java.awt.Color(255, 255, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Título      :");

        jlblPeliculaTitulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblPeliculaTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jlblPeliculaTitulo.setText("Titulo");
        jlblPeliculaTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblPeliculaTituloMouseClicked(evt);
            }
        });

        jlblPeliculaGenero.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblPeliculaGenero.setForeground(new java.awt.Color(255, 255, 255));
        jlblPeliculaGenero.setText("Género");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Género    :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Duración :");

        jlblPeliculaDuracion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblPeliculaDuracion.setForeground(new java.awt.Color(255, 255, 255));
        jlblPeliculaDuracion.setText("Duración");

        jlblPeliculaPais.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblPeliculaPais.setForeground(new java.awt.Color(255, 255, 255));
        jlblPeliculaPais.setText("País");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("País         : ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Director   :");

        jlblPeliculaDirector.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblPeliculaDirector.setForeground(new java.awt.Color(255, 255, 255));
        jlblPeliculaDirector.setText("Director");

        jtxaPeliculaActores.setBackground(new java.awt.Color(0, 0, 0));
        jtxaPeliculaActores.setColumns(20);
        jtxaPeliculaActores.setForeground(new java.awt.Color(255, 255, 255));
        jtxaPeliculaActores.setRows(5);
        jScrollPane2.setViewportView(jtxaPeliculaActores);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Actores   :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlblPeliculaPais, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlblPeliculaTituloGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(17, 17, 17)
                            .addComponent(jlblPeliculaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(17, 17, 17)
                            .addComponent(jlblPeliculaGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(18, 18, 18)
                            .addComponent(jlblPeliculaDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel8)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(15, 15, 15)
                            .addComponent(jlblPeliculaDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(7, 7, 7)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jlblPeliculaTituloGrande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jlblPeliculaPais)
                .addContainerGap(124, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jlblPeliculaTitulo))
                    .addGap(5, 5, 5)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(jlblPeliculaGenero))
                    .addGap(5, 5, 5)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addComponent(jlblPeliculaDuracion))
                    .addGap(5, 5, 5)
                    .addComponent(jLabel8)
                    .addGap(5, 5, 5)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9)
                        .addComponent(jlblPeliculaDirector))
                    .addGap(5, 5, 5)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 20, Short.MAX_VALUE)))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)), "Sinopsis", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(255, 102, 0)));

        jtxaPeliculaSinopsis.setBackground(new java.awt.Color(0, 0, 0));
        jtxaPeliculaSinopsis.setColumns(20);
        jtxaPeliculaSinopsis.setForeground(new java.awt.Color(255, 255, 255));
        jtxaPeliculaSinopsis.setRows(5);
        jScrollPane1.setViewportView(jtxaPeliculaSinopsis);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(35, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(30, 30, 30)))
        );

        jlblImagenCatalogoPeliculas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/AF0481.jpg"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("DETALLE DE LA PELÍCULA");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/estrella.png"))); // NOI18N
        jLabel3.setText("jLabel1");

        jbtnPeliculaAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/atras.png"))); // NOI18N
        jbtnPeliculaAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPeliculaAnteriorActionPerformed(evt);
            }
        });

        jbtnPeliculaSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/siguiente.png"))); // NOI18N
        jbtnPeliculaSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPeliculaSiguienteActionPerformed(evt);
            }
        });

        jlblPeliculaGeneroSeleccionado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblPeliculaGeneroSeleccionado.setForeground(new java.awt.Color(255, 255, 255));
        jlblPeliculaGeneroSeleccionado.setText("TODOS LOS GÉNEROS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlblImagenCatalogoPeliculas)
                                .addGap(35, 35, 35))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jbtnPeliculaAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)))
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnPeliculaSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(347, 347, 347))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jlblPeliculaGeneroSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(192, 192, 192)
                        .addComponent(jbtnPeliculaSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jlblPeliculaGeneroSeleccionado, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlblImagenCatalogoPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jbtnPeliculaAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(504, 504, 504))))))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel20))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel20)
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnVerPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVerPeliculasActionPerformed
try {
           Conexion1 con = new Conexion1();
            con.conectar();
           // ResultSet exito = (ResultSet) con.dameLista(query+" upper('%"+this.jtxtfValorBusqueda.getText().toString()+"%')");
          boolean exito = con.ejecurarConsulta(query+" upper('%"+this.jtxfBuscarPorTitulo.getText().toString()+"%')");
            val = new ArrayList<String[]>();
           if(exito){
                while (con.rs.next()) {                
                    String[] aux = new String[col];
                    for (int i = 0; i < aux.length; i++) {
                        aux[i] = String.valueOf(con.rs.getObject(i+1));
                        
                    }
                    val.add(aux);                  
                }
            }
            jtblDetalle.setModel(new ModeloTabla(col, nom, val));
        } catch (SQLException ex) {
            ex.printStackTrace();
        }           
    }//GEN-LAST:event_jbtnVerPeliculasActionPerformed

    private void jlblPeliculaTituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblPeliculaTituloMouseClicked

   }//GEN-LAST:event_jlblPeliculaTituloMouseClicked

    private void jbtnPeliculaAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPeliculaAnteriorActionPerformed
        if (i > 0) {
            i--;
            if (this.activoVerTodosLosGeneros) {
                mostrarCatalogoPeliculasTodosLosGeneros();
            } else {
                mostrarCatalogoPeliculasPorGenero(genero);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Llego al inicio del catálogo.\n No hay más Películas");

        }
    }//GEN-LAST:event_jbtnPeliculaAnteriorActionPerformed

    private void jbtnPeliculaSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPeliculaSiguienteActionPerformed
        if (i < (this.listaPeliculas.size() - 1)) {
            i++;
            if (this.activoVerTodosLosGeneros) {
                mostrarCatalogoPeliculasTodosLosGeneros();
            } else {
                mostrarCatalogoPeliculasPorGenero(genero);
            }
        } else {
            JOptionPane.showMessageDialog(this, "LLego al final del catálogo.\n No hay más Peliculas");
        }
    }//GEN-LAST:event_jbtnPeliculaSiguienteActionPerformed

    private void jtblDetalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblDetalleMouseClicked
    
        for (int i = 0; i < tfParam.length; i++) {
        if(jtblDetalle.getValueAt(jtblDetalle.getSelectedRow(),i) != null) {
            if ( tfParam[i] instanceof JTextField ) {
                 //System.out.println(((JTextField)tfParam[i]).getName());
                ((JTextField)tfParam[i]).setText(jtblDetalle.getValueAt(jtblDetalle.getSelectedRow(),i).toString());
            }
            else if(tfParam[i] instanceof JComboBox){
                int indice =Integer.parseInt(jtblDetalle.getValueAt(jtblDetalle.getSelectedRow(),i).toString());
                //System.out.print(indice);
                ((JComboBox)tfParam[i]).setSelectedIndex(indice);
                    //DropDown itemcbo = (DropDown)((JComboBox)tfParam[i]).getItemAt(indice);
                    //System.out.println(itemcbo.getCodigo());
            }
            
         
        }
       String cod = "",des  = "";
         fila = jtblDetalle.getSelectedRow();
         
         int cod_col=Integer.parseInt(jtblDetalle.getValueAt(fila,0).toString());
        
        ConeccionBD1 z = new ConeccionBD1();
        Connection cn = z.conectar();       
         String sql = "SELECT * from vistapelicula  "+
                 " WHERE Codigo= "+ cod_col;
       try {
                 Statement st = cn.createStatement();
                 rs = st.executeQuery(sql);
                while (rs.next())
                {
                  jlblImagenCatalogoPeliculas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/" + cod_col + ".jpg")));
               // cod = rs.getString("");
               jlblPeliculaTituloGrande.setText(rs.getString("Pelicula"));
               jlblPeliculaTitulo.setText(rs.getString("Pelicula"));
               jlblPeliculaGenero.setText(rs.getString("Genero"));
               jlblPeliculaDuracion.setText(rs.getString("Duraccion"));
               jlblPeliculaDirector.setText(rs.getString("Director"));
               jtxaPeliculaActores.setText(rs.getString("Actores"));
               jlblPeliculaPais.setText(rs.getString("Pais"));
               jtxaPeliculaSinopsis.setText(rs.getString("Sinopsis"));
                
               
               
       
            }
           
            
            
                
        }
        
        catch (SQLException ex) 
        {
            JOptionPane.showMessageDialog(null, ex);
        }
            //tfParam[i].setText(jtblDetalleBusqueda.getValueAt(jtblDetalleBusqueda.getSelectedRow(),i).toString());
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jtblDetalleMouseClicked

    /**
     * @param args the command line arguments
     */
     public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
 //               new VentanaBuscar("select id, rsocial, telefono from proveedores where rsocial like '", new String[]{"CODIGO","DESCRIPCION","TELEFONO"},3).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbtnPeliculaAnterior;
    private javax.swing.JButton jbtnPeliculaSiguiente;
    private javax.swing.JButton jbtnVerPeliculas;
    private javax.swing.JLabel jlblImagenCatalogoPeliculas;
    private javax.swing.JLabel jlblPeliculaDirector;
    private javax.swing.JLabel jlblPeliculaDuracion;
    private javax.swing.JLabel jlblPeliculaGenero;
    private javax.swing.JLabel jlblPeliculaGeneroSeleccionado;
    private javax.swing.JLabel jlblPeliculaPais;
    private javax.swing.JLabel jlblPeliculaTitulo;
    private javax.swing.JTextField jlblPeliculaTituloGrande;
    private javax.swing.JTable jtblDetalle;
    private javax.swing.JTextArea jtxaPeliculaActores;
    private javax.swing.JTextArea jtxaPeliculaSinopsis;
    private javax.swing.JTextField jtxfBuscarPorTitulo;
    private javax.swing.JPanel lo;
    // End of variables declaration//GEN-END:variables

private boolean existeTituloPelicula(String titulo) {
        return bd.existeTituloPelicula(titulo);
    }

    private Pelicula obtenerPeliculaPorTitulo(String titulo) {
        return bd.obtenerPeliculaPorTitulo(titulo);
    }

    private void mostrarCatalogoPeliculasPorGenero(Genero genero) {
        listaPeliculas = bd.getPeliculasPorGenero(genero);
        if (listaPeliculas != null) {
            if (listaPeliculas.size() != 0) {
                pelicula = listaPeliculas.get(i);
                this.jlblImagenCatalogoPeliculas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/" + this.pelicula.getId() + ".jpg")));
                this.jlblPeliculaTituloGrande.setText(this.pelicula.getTitulo());
                this.jlblPeliculaTitulo.setText(this.pelicula.getTitulo());
                this.jlblPeliculaGenero.setText(this.pelicula.getGenero().getDescripcion());
                this.jlblPeliculaDuracion.setText(this.pelicula.getDuracion());
                this.jlblPeliculaPais.setText(this.pelicula.getPais());
                this.jlblPeliculaDirector.setText(this.pelicula.getDirector());
                this.jtxaPeliculaActores.setText(this.pelicula.getActores());
                this.jtxaPeliculaSinopsis.setText(this.pelicula.getSinopsis());
            }
        }
    }

    private void mostrarCatalogoPeliculasTodosLosGeneros() {
        this.listaPeliculas = bd.obtenerPeliculasDeTodosLosGeneros();
        if (listaPeliculas != null) {
            if (listaPeliculas.size() != 0) {
                pelicula = listaPeliculas.get(i);
                this.jlblImagenCatalogoPeliculas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/" + this.pelicula.getId() + ".jpg")));
                this.jlblPeliculaTituloGrande.setText(this.pelicula.getTitulo());
                this.jlblPeliculaTitulo.setText(this.pelicula.getTitulo());
                this.jlblPeliculaGenero.setText(this.pelicula.getGenero().getDescripcion());
                this.jlblPeliculaDuracion.setText(this.pelicula.getDuracion());
                this.jlblPeliculaPais.setText(this.pelicula.getPais());
                this.jlblPeliculaDirector.setText(this.pelicula.getDirector());
                this.jtxaPeliculaActores.setText(this.pelicula.getActores());
                this.jtxaPeliculaSinopsis.setText(this.pelicula.getSinopsis());
            }
        }
    }

}
